In [9]:
""" An in-depth-analysis of JSON files related to MIbact libraries from 2010 to 2018. Some of the information considered were the library heritage dimension, the number of borrowings to privates and other libraries,
 consulted works, and number of readers. These aspect have been assessed for all the Mibact Libriaries distributed across the country. The  main idea of this analysis was 
 to understand the level of people's enjoyment of cultural products within free access institutions such as Mibact libraries."""

#Dataframes and JSON files of Biblioteche Mibact - Anno 2010

import pandas as pd
import json
from IPython.display import display

json_path=r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Biblio_Mibact_Statali_Ministero_2010.json"
with open(json_path, 'r', encoding='utf-8') as file:
    json_data = json.load(file)


# Rimuovere i valori null
cleaned_data = {key: [entry for entry in value if entry is not None] for key, value in json_data.items()}

# Convertire in DataFrame + cleaning del file json di partenza
df_tav_4_7 = pd.DataFrame(cleaned_data["Tav 4.7"])
df_tav_4_7 = df_tav_4_7.replace('\n', '', regex=True)
df_tav_4_7= df_tav_4_7.fillna(value='')
df_tav_4_8 = pd.DataFrame(cleaned_data["Tav 4.8"])
df_tav_4_8= df_tav_4_8.fillna(value='')
df_tav_4_9 = pd.DataFrame(cleaned_data["Tav 4.9"])
df_tav_4_9 = df_tav_4_9.replace('\n', ' ', regex=True)
df_tav_4_9= df_tav_4_9.fillna(value='')
df_tav_4_10 = pd.DataFrame(cleaned_data["Tav 4.10"])
df_tav_4_10 = df_tav_4_10.replace('\n', ' ', regex=True)
df_tav_4_10= df_tav_4_10.fillna(value='')
df_tav_4_10 = df_tav_4_10[['Column2', 'Column4', 'Column5', 'Column7']]
df_tav_4_10=df_tav_4_10.rename(columns={"Column2" : "Column3", "Column7": "Column6"})

#Rename Columns
df_tav_1=df_tav_4_7.rename(columns={
    "Tavola 4.7 - Biblioteche, opere consultate, prestiti e personale delle biblioteche statali dipendenti dal Ministero per i beni e le attivit√† culturali per provincia - Anno 2010": 'Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2010' 
})
df_tav_1 = df_tav_1.drop(columns=['Column6', "Column5"])
df_tav_1=df_tav_1.rename(columns={"Column3" : "Column2", "Column4": "Column7"})
df_tav_1=pd.concat([df_tav_1, df_tav_4_10], axis=1)
ordered_columns = ['Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2010',  'Column2', 'Column3', 'Column4', 'Column5', 'Column6', 'Column7']
df_tav_1 = df_tav_1.reindex(columns=ordered_columns)
display(df_tav_1)

df_tav_2=df_tav_4_8.rename(columns={"Tavola 4.8 - Biblioteche statali dipendenti dal MiBact per tipologia e provincia  e consistenza del patrimonio librario - Anno 2010": 'Tav. 2 - Biblioteche statali dipendenti dal MiBact per tipologia e provincia  e consistenza del patrimonio librario - Anno 2010'})
display(df_tav_2)

df_tav_3 = df_tav_4_9.rename(columns={"Tavola 4.9 - Biblioteche statali dipendenti dal MiBact, posti per lettori, lettori in totale e stranieri e opere consultate - Anno 2010": "Tav. 3 - Biblioteche statali dipendenti dal MiBact, posti per lettori, lettori in totale e stranieri - Anno 2010" })
df_tav_3 = df_tav_3.drop(columns=['Column6'])
display(df_tav_3)



json_path_tav_1 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_1_prestiti_2010.json"
json_path_tav_2 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_2_patrimonio_2010.json"
json_path_tav_3 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_3_lettura_2010.json"



#Save df_tav_1 to JSON
df_tav_1.to_json(json_path_tav_1, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_1, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_1, 'w') as f:
    f.write(data)
    
with open(json_path_tav_1, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_1, 'w') as f:
    f.write(modified_json)
    

# Save df_tav_2 to JSON
df_tav_2.to_json(json_path_tav_2, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_2, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_2, 'w') as f:
    f.write(data)
    
with open(json_path_tav_2, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_2, 'w') as f:
    f.write(modified_json)
    

#Save df_tav_3 to JSON
df_tav_3.to_json(json_path_tav_3, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_3, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_3, 'w') as f:
    f.write(data)
    
with open(json_path_tav_3, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_3, 'w') as f:
    f.write(modified_json)

,"Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2010",Column2,Column3,Column4,Column5,Column6,Column7
0,PROVINCE E REGIONI,Biblioteche,Persone ammesse al prestito,Opere in prestito a privati,Opere in prestito a biblioteche,Opere ricevute in prestito da biblioteche,Opere consultate
1,Torino,2,64961,16775,1015,315,86444
2,Piemonte,2,64961,16775,1015,315,86444
3,Valle d'Aosta/Vall√©e d'Aoste,-,-,-,-,-,-
4,Cremona,1,2148,16743,1085,936,225551
5,Milano,1,1451,10162,2570,263,32413
6,Pavia,1,2306,6315,561,174,18878
7,Lombardia,3,5905,33220,4216,1373,276842
8,Bolzano/Bozen,-,-,-,-,-,-
9,Trento,-,-,-,-,-,-
10,Trentino-Alto Adige,-,-,-,-,-,-
11,Padova,3,2758,9082,839,336,40594
12,Venezia,1,1479,4584,927,273,56539
13,Veneto,4,4237,13666,1766,609,97133
14,Gorizia,1,5406,13050,613,377,56277
15,Trieste,1,1438,5922,138,177,28380
16,Friuli-Venezia Giulia,2,6844,18972,751,554,84657
17,Genova,1,2050,6800,528,705,17718
18,Liguria,1,2050,6800,528,705,17718
19,Modena,1,1281,4829,747,158,23629
20,Parma,1,8815,4465,155,67,12476
21,Emilia-Romagna,2,10096,9294,902,225,36105
22,Firenze,4,6784,13494,1907,200,513061
23,Lucca,1,2562,1893,558,316,13275
24,Pisa,1,626,964,312,121,9223
25,Toscana,6,9972,16351,2777,637,535559
26,Umbria,-,-,-,-,-,-
27,Macerata,1,3820,8542,140,50,26900
28,Marche,1,3820,8542,140,50,26900
29,Frosinone,3,0,0,0,0,24306
30,Rieti,1,15,42,0,0,750
31,Roma,11,40048,53970,2860,823,526021
32,Lazio,15,40063,54012,2860,823,551077
33,Abruzzo,-,-,-,-,-,-
34,Molise,-,-,-,-,-,-
35,Avellino,1,2005,922,49,235,10818
36,Napoli,3,4469,13427,584,686,161936
37,Salerno,1,25,194,0,1,3200
38,Campania,5,6499,14543,633,922,175954
39,Bari,1,573,2158,385,72,9024
40,Puglia,1,573,2158,385,72,9024
41,Potenza,1,687,2529,111,227,11390
42,Basilicata,1,687,2529,111,227,11390
43,Cosenza,1,660,2842,484,310,6692
44,Calabria,1,660,2842,484,310,6692
45,Sicilia,-,-,-,-,-,-
46,Cagliari,1,6549,9429,468,389,62871
47,Sassari,1,2689,2030,411,129,1356
48,Sardegna,2,9238,11459,879,518,64227
49,,,,,,,
50,ITALIA,46,165605,211163,17447,7340,1979722
51,Nord,14,94093,98727,9178,3781,598899
52,Centro,22,53855,78905,5777,1510,1113536
53,Mezzogiorno,10,17657,33531,2492,2049,267287

,Tav. 2 - Biblioteche statali dipendenti dal MiBact per tipologia e provincia e consistenza del patrimonio librario - Anno 2010,Column3,Column4,Column5,Column6
0,PROVINCE E REGIONI,Volumi manoscritti,Volumi stampati,Opuscoli,Periodici
1,Torino,8978,945901,203000,1392
2,Piemonte,8978,945901,203000,1392
3,Valle d'Aosta/Vall√©e d'Aoste,-,-,-,-
4,Cremona,3871,473640,86404,117
5,Milano,2119,985272,299086,3355
6,Pavia,1411,384135,118179,221
7,Lombardia,7401,1843047,503669,3693
8,Bolzano/Bozen,-,-,-,-
9,Trento,-,-,-,-
10,Trentino-Alto Adige,-,-,-,-
11,Padova,2944,603132,227039,1076
12,Venezia,13118,632602,262710,848
13,Veneto,16062,1235734,489749,1924
14,Gorizia,867,282377,54082,644
15,Trieste,8,187813,19001,238
16,Friuli-Venezia Giulia,875,470190,73083,882
17,Genova,1949,395477,102252,1117
18,Liguria,1949,395477,102252,1117
19,Modena,11025,562491,129181,571
20,Parma,52244,671115,130942,341
21,Emilia-Romagna,63269,1233606,260123,912
22,Firenze,43434,6295714,2926627,9238
23,Lucca,4323,378036,87591,580
24,Pisa,1392,454414,104848,1850
25,Toscana,49149,7128164,3119066,11668
26,Umbria,-,-,-,-
27,Macerata,64,78198,3737,350
28,Marche,64,78198,3737,350
29,Frosinone,2680,176145,5346,228
30,Rieti,350,43820,2444,51
31,Roma,25013,6655845,1999096,28702
32,Lazio,28043,6875810,2006886,28981
33,Abruzzo,-,-,-,-
34,Molise,-,-,-,-
35,Avellino,580,152983,22367,144
36,Napoli,19112,2332326,466408,6389
37,Salerno,438,81386,6409,70
38,Campania,20130,2566695,495184,6603
39,Bari,454,298014,65456,720
40,Puglia,454,298014,65456,720
41,Potenza,74,125585,11335,490
42,Basilicata,74,125585,11335,490
43,Cosenza,116,109748,13866,167
44,Calabria,116,109748,13866,167
45,Sicilia,-,-,-,-
46,Cagliari,604,541226,29877,843
47,Sassari,916,198014,25009,1974
48,Sardegna,1520,739240,54886,2817
49,,,,,
50,ITALIA,198084,24045409,7402292,61716
51,Nord,98534,6123955,1631876,9920
52,Centro,77256,14082172,5129689,40999
53,Mezzogiorno,22294,3839282,640727,10797

,"Tav. 3 - Biblioteche statali dipendenti dal MiBact, posti per lettori, lettori in totale e stranieri - Anno 2010",Column2,Column4,Column5
0,PROVINCE E REGIONI,Posti per lettori,Lettori Totali,Lettori Stranieri
1,Torino,420,106707,5520
2,Piemonte,420,106707,5520
3,Valle d'Aosta/Vall√©e d'Aoste,-,-,-
4,Cremona,220,109161,9824
5,Milano,240,64947,6707
6,Pavia,63,41131,1310
7,Lombardia,523,215239,17841
8,Bolzano/Bozen,-,-,-
9,Trento,-,-,-
10,Trentino-Alto Adige,-,-,-
11,Padova,252,55251,789
12,Venezia,76,31342,9800
13,Veneto,328,86593,10589
14,Gorizia,102,51833,1250
15,Trieste,120,23660,1098
16,Friuli-Venezia Giulia,222,75493,2348
17,Genova,99,59127,8212
18,Liguria,99,59127,8212
19,Modena,220,23888,2921
20,Parma,142,50992,5352
21,Emilia-Romagna,362,74880,8273
22,Firenze,589,196217,27381
23,Lucca,80,11592,80
24,Pisa,120,6330,103
25,Toscana,789,214139,27564
26,Umbria,-,-,-
27,Macerata,104,20503,3570
28,Marche,104,20503,3570
29,Frosinone,82,9729,591
30,Rieti,40,395,5
31,Roma,1860,408580,16873
32,Lazio,1982,418704,17469
33,Abruzzo,-,-,-
34,Molise,-,-,-
35,Avellino,116,2320,6
36,Napoli,694,92421,1444
37,Salerno,18,818,14
38,Campania,828,95559,1464
39,Bari,230,24017,310
40,Puglia,230,24017,310
41,Potenza,313,47654,343
42,Basilicata,313,47654,343
43,Cosenza,65,8132,114
44,Calabria,65,8132,114
45,Sicilia,-,-,-
46,Cagliari,98,22322,863
47,Sassari,140,11174,-
48,Sardegna,238,33496,863
49,,,,
50,ITALIA,6503,1480243,104480
51,Nord,1954,618039,52783
52,Centro,2875,653346,48603
53,Mezzogiorno,1674,208858,3094

In [10]:
#Dataframes and JSON files of Biblioteche Mibact - Anno 2011

import pandas as pd
import json
from IPython.display import display

json_path=r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Biblio_Mibact_Statali_Ministero_2011.json"
with open(json_path, 'r', encoding='utf-8') as file:
    json_data = json.load(file)


# Rimuovere i valori null
cleaned_data = {key: [entry for entry in value if entry is not None] for key, value in json_data.items()}

# Convertire in DataFrame
df_tav_4_7 = pd.DataFrame(cleaned_data["Tav 4.7"])
df_tav_4_7 = df_tav_4_7.replace('\n', '', regex=True)
df_tav_4_7= df_tav_4_7.fillna(value='')
df_tav_4_8 = pd.DataFrame(cleaned_data["Tav 4.8"])
df_tav_4_8= df_tav_4_8.fillna(value='')
df_tav_4_9 = pd.DataFrame(cleaned_data["Tav 4.9"])
df_tav_4_9 = df_tav_4_9.replace('\n', ' ', regex=True)
df_tav_4_9= df_tav_4_9.fillna(value='')
df_tav_4_10 = pd.DataFrame(cleaned_data["Tav 4.10"])
df_tav_4_10= df_tav_4_10.fillna(value='')
df_tav_4_10 = df_tav_4_10[['Column2', 'Column4', 'Column5', 'Column6']]
df_tav_4_10=df_tav_4_10.rename(columns={"Column2" : "Column3"})

#Rename columns
df_tav_1=df_tav_4_7.rename(columns={
    "Tavola 4.7 - Biblioteche, opere consultate, prestiti e personale delle biblioteche statali dipendenti dal Ministero per i beni e le attivit√† culturali per provincia - Anno 2011": 'Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2011' 
})
df_tav_1 = df_tav_1.drop(columns=['Column6', "Column5"])
df_tav_1=df_tav_1.rename(columns={"Column3" : "Column2", "Column4": "Column7"})
df_tav_1=pd.concat([df_tav_1, df_tav_4_10], axis=1)
ordered_columns = ['Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2011',  'Column2', 'Column3', 'Column4', 'Column5', 'Column6', 'Column7']
df_tav_1 = df_tav_1.reindex(columns=ordered_columns)
display(df_tav_1)

df_tav_2=df_tav_4_8.rename(columns={"Tavola 4.8 - Biblioteche statali dipendenti dal MiBact per tipologia e provincia  e consistenza del patrimonio librario - Anno 2011": 'Tav. 2 - Biblioteche statali dipendenti dal MiBact per tipologia e provincia  e consistenza del patrimonio librario - Anno 2011'})
display(df_tav_2)

df_tav_3 = df_tav_4_9.rename(columns={"Tavola 4.9 - Biblioteche statali dipendenti dal MiBact, posti per lettori, lettori in totale e stranieri e opere consultate - Anno 2011": "Tav. 3 - Biblioteche statali dipendenti dal MiBact, posti per lettori, lettori in totale e stranieri - Anno 2011" })
df_tav_3 = df_tav_3.drop(columns=['Column6'])
display(df_tav_3)



json_path_tav_1 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_1_prestiti_2011.json"
json_path_tav_2 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_2_patrimonio_2011.json"
json_path_tav_3 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_3_lettura_2011.json"



#Save df_tav_1 to JSON
df_tav_1.to_json(json_path_tav_1, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_1, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_1, 'w') as f:
    f.write(data)
    
with open(json_path_tav_1, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_1, 'w') as f:
    f.write(modified_json)
    

# Save df_tav_2 to JSON
df_tav_2.to_json(json_path_tav_2, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_2, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_2, 'w') as f:
    f.write(data)
    
with open(json_path_tav_2, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_2, 'w') as f:
    f.write(modified_json)
    

#Save df_tav_3 to JSON
df_tav_3.to_json(json_path_tav_3, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_3, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_3, 'w') as f:
    f.write(data)
    
with open(json_path_tav_3, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_3, 'w') as f:
    f.write(modified_json)

,"Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2011",Column2,Column3,Column4,Column5,Column6,Column7
0,PROVINCE E REGIONI,Biblioteche,Persone ammesse al prestito,Opere in prestito a privati,Opere in prestito a biblioteche,Opere ricevute in prestito da biblioteche,Opere consultate
1,Torino,2,79793,14548,727,191,77591
2,Piemonte,2,79793,14548,727,191,77591
3,Valle d'Aosta/Vall√©e d'Aoste,-,-,-,-,-,-
4,Cremona,1,2051,16273,953,853,240940
5,Milano,1,1408,9516,2385,221,17632
6,Pavia,1,2013,5998,505,242,20245
7,Lombardia,3,5472,31787,3843,1316,278817
8,Bolzano/Bozen,-,-,-,-,-,-
9,Trento,-,-,-,-,-,-
10,Trentino-Alto Adige,-,-,-,-,-,-
11,Padova,3,2918,7472,834,227,41204
12,Venezia,1,1500,4826,908,219,39600
13,Veneto,4,4418,12298,1742,446,80804
14,Gorizia,1,4700,12934,542,318,59383
15,Trieste,1,1348,5776,142,196,24483
16,Friuli-Venezia Giulia,2,6048,18710,684,514,83866
17,Genova,1,2539,5945,461,659,16333
18,Liguria,1,2539,5945,461,659,16333
19,Modena,1,1098,4450,670,169,23640
20,Parma,1,1404,3228,297,94,12674
21,Emilia-Romagna,2,2502,7678,967,263,36314
22,Firenze,4,3992,12062,1920,113,518765
23,Lucca,1,2573,1874,399,281,10562
24,Pisa,1,5003,1787,240,150,10500
25,Toscana,6,11568,15723,2559,544,539827
26,Umbria,-,-,-,-,-,-
27,Macerata,1,3910,8669,163,71,23400
28,Marche,1,3910,8669,163,71,23400
29,Frosinone,3,-,-,-,-,26026
30,Rieti,1,18,49,-,-,680
31,Roma,11,37986,56477,3085,700,559371
32,Lazio,15,38004,56526,3085,700,586077
33,Abruzzo,-,-,-,-,-,-
34,Molise,-,-,-,-,-,-
35,Avellino,1,2368,1044,98,440,8286
36,Napoli,2,4803,10135,387,694,952526
37,Salerno,1,27,226,-,1,2046
38,Campania,4,7198,11405,485,1135,962858
39,Bari,1,456,2020,369,32,6725
40,Puglia,1,456,2020,369,32,6725
41,Potenza,1,600,3080,129,170,10112
42,Basilicata,1,600,3080,129,170,10112
43,Cosenza,1,686,2552,470,289,4383
44,Calabria,1,686,2552,470,289,4383
45,Sicilia,-,-,-,-,-,-
46,Cagliari,1,5840,8358,382,447,51312
47,Sassari,1,2517,1982,257,90,1450
48,Sardegna,2,8357,10340,639,537,52762
49,,,,,,,
50,ITALIA,45,171551,201281,16323,6867,2759869
51,Nord,14,100772,90966,8424,3389,573725
52,Centro,22,53482,80918,5807,1315,1149304
53,Mezzogiorno,9,17297,29397,2092,2163,1036840

,Tav. 2 - Biblioteche statali dipendenti dal MiBact per tipologia e provincia e consistenza del patrimonio librario - Anno 2011,Column3,Column4,Column5,Column6
0,PROVINCE E REGIONI,Volumi manoscritti,Volumi stampati,Opuscoli,Periodici
1,Torino,8978,952756,204298,1130
2,Piemonte,8978,952756,204298,1130
3,Valle d'Aosta/Vall√©e d'Aoste,-,-,-,-
4,Cremona,3874,474844,86478,93
5,Milano,2119,1000963,299299,3512
6,Pavia,1411,385689,119379,161
7,Lombardia,7404,1861496,505156,3766
8,Bolzano/Bozen,-,-,-,-
9,Trento,-,-,-,-
10,Trentino-Alto Adige,-,-,-,-
11,Padova,2944,605933,228052,1092
12,Venezia,13118,634297,262848,746
13,Veneto,16062,1240230,490900,1838
14,Gorizia,876,352566,79732,593
15,Trieste,8,188256,19276,213
16,Friuli-Venezia Giulia,884,540822,99008,806
17,Genova,1949,398907,102814,1048
18,Liguria,1949,398907,102814,1048
19,Modena,11025,564291,129337,485
20,Parma,52244,673419,130942,341
21,Emilia-Romagna,63269,1237710,260279,826
22,Firenze,43436,6362155,2929167,11875
23,Lucca,4323,379001,87831,247
24,Pisa,1392,475635,105342,1912
25,Toscana,49151,7216791,3122340,14034
26,Umbria,-,-,-,-
27,Macerata,64,79375,3992,353
28,Marche,64,79375,3992,353
29,Frosinone,2680,176751,5346,138
30,Rieti,350,43968,2444,-
31,Roma,25014,6756046,2001542,32876
32,Lazio,28044,6976765,2009332,33014
33,Abruzzo,-,-,-,-
34,Molise,-,-,-,-
35,Avellino,580,153903,22564,144
36,Napoli,18566,2166257,449692,1319
37,Salerno,438,82399,6662,74
38,Campania,19584,2402559,478918,1537
39,Bari,454,302630,65507,270
40,Puglia,454,302630,65507,270
41,Potenza,74,128187,11545,510
42,Basilicata,74,128187,11545,510
43,Cosenza,117,113051,14119,179
44,Calabria,-,-,-,-
45,Sicilia,117,113051,14119,179
46,Cagliari,604,542910,29902,807
47,Sassari,916,198555,25009,1976
48,Sardegna,1520,741465,54911,2783
49,,,,,
50,ITALIA,197554,24192744,7423119,62094
51,Nord,98546,6231921,1662455,9414
52,Centro,77259,14272931,5135664,47401
53,Mezzogiorno,21749,3687892,625000,5279

,"Tav. 3 - Biblioteche statali dipendenti dal MiBact, posti per lettori, lettori in totale e stranieri - Anno 2011",Column2,Column4,Column5
0,PROVINCE E REGIONI,Posti per lettori,Lettori in totale,Lettori Stranieri
1,Torino,416,154949,6609
2,Piemonte,416,154949,6609
3,Valle d'Aosta/Vall√©e d'Aoste,-,-,-
4,Cremona,220,116482,12824
5,Milano,240,65122,9768
6,Pavia,63,36208,1114
7,Lombardia,523,217812,23706
8,Bolzano/Bozen,-,-,-
9,Trento,-,-,-
10,Trentino-Alto Adige,-,-,-
11,Padova,252,53173,636
12,Venezia,76,38958,8700
13,Veneto,328,92131,9336
14,Gorizia,102,47802,1132
15,Trieste,120,21692,1084
16,Friuli-Venezia Giulia,222,69494,2216
17,Genova,99,49610,7945
18,Liguria,99,49610,7945
19,Modena,220,28022,6250
20,Parma,142,22876,2987
21,Emilia-Romagna,362,50898,9237
22,Firenze,589,193273,27567
23,Lucca,80,11163,66
24,Pisa,120,6829,139
25,Toscana,789,211265,27772
26,Umbria,-,-,-
27,Macerata,104,22358,4780
28,Marche,104,22358,4780
29,Frosinone,84,9977,685
30,Rieti,40,363,8
31,Roma,1870,414618,21315
32,Lazio,1994,424958,22008
33,Abruzzo,-,-,-
34,Molise,-,-,-
35,Avellino,116,2222,5
36,Napoli,614,74713,1131
37,Salerno,18,863,27
38,Campania,748,77798,1163
39,Bari,230,22068,335
40,Puglia,230,22068,335
41,Potenza,313,49359,-
42,Basilicata,313,49359,-
43,Cosenza,65,11849,36
44,Calabria,65,11849,36
45,Sicilia,-,-,-
46,Cagliari,98,21977,1338
47,Sassari,140,10513,-
48,Sardegna,238,32490,1338
49,,,,
50,ITALIA,6431,1487039,116481
51,Nord,1950,634894,59049
52,Centro,2887,658581,54560
53,Mezzogiorno,1594,193564,2872

In [11]:
#Dataframes and JSON files of Biblioteche Mibact - Anno 2012

import pandas as pd
import json
from IPython.display import display

json_path=r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Biblio_Mibact_Statali_Ministero_2012.json"
with open(json_path, 'r', encoding='utf-8') as file:
    json_data = json.load(file)


# Rimuovere i valori null
cleaned_data = {key: [entry for entry in value if entry is not None] for key, value in json_data.items()}

# Convertire in DataFrame
df_tav_4_7 = pd.DataFrame(cleaned_data["Tav 4.7"])
df_tav_4_7 = df_tav_4_7.replace('\n', '', regex=True)
df_tav_4_7= df_tav_4_7.fillna(value='')
df_tav_4_8 = pd.DataFrame(cleaned_data["Tav 4.8"])
df_tav_4_8= df_tav_4_8.fillna(value='')
df_tav_4_9 = pd.DataFrame(cleaned_data["Tav 4.9"])
df_tav_4_9 = df_tav_4_9.replace('\n', ' ', regex=True)
df_tav_4_9= df_tav_4_9.fillna(value='')
df_tav_4_10 = pd.DataFrame(cleaned_data["Tav 4.10"])
df_tav_4_10 = df_tav_4_10.replace('\n', ' ', regex=True)
df_tav_4_10= df_tav_4_10.fillna(value='')
df_tav_4_10 = df_tav_4_10[['Column2', 'Column4', 'Column5', 'Column7']]
df_tav_4_10=df_tav_4_10.rename(columns={"Column2" : "Column3", 'Column7': 'Column6'})

#Rename columns
df_tav_1=df_tav_4_7.rename(columns={
    "Tavola 4.7 - Biblioteche, opere consultate, prestiti e personale delle biblioteche statali dipendenti dal Ministero per i beni e le attivit√† culturali per provincia - Anno 2012": 'Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2012' 
})
df_tav_1 = df_tav_1.drop(columns=['Column6', "Column5"])
df_tav_1=df_tav_1.rename(columns={"Column3" : "Column2", "Column4": "Column7"})
df_tav_1=pd.concat([df_tav_1, df_tav_4_10], axis=1)
ordered_columns = ['Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2012',  'Column2', 'Column3', 'Column4', 'Column5', 'Column6', 'Column7']
df_tav_1 = df_tav_1.reindex(columns=ordered_columns)
display(df_tav_1)

df_tav_2=df_tav_4_8.rename(columns={"Tavola 4.8 - Biblioteche statali dipendenti dal MiBact per tipologia e provincia  e consistenza del patrimonio librario - Anno 2012": 'Tav. 2 - Biblioteche statali dipendenti dal MiBact per tipologia e provincia  e consistenza del patrimonio librario - Anno 2012'})
display(df_tav_2)

df_tav_3 = df_tav_4_9.rename(columns={"Tavola 4.9 - Biblioteche statali dipendenti dal MiBact, posti per lettori, lettori in totale e stranieri e opere consultate - Anno 2012": "Tav. 3 - Biblioteche statali dipendenti dal MiBact, posti per lettori, lettori in totale e stranieri - Anno 2012"})
df_tav_3 = df_tav_3.drop(columns=['Column6'])
display(df_tav_3)



json_path_tav_1 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_1_prestiti_2012.json"
json_path_tav_2 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_2_patrimonio_2012.json"
json_path_tav_3 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_3_lettura_2012.json"



#Save df_tav_1 to JSON
df_tav_1.to_json(json_path_tav_1, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_1, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_1, 'w') as f:
    f.write(data)
    
with open(json_path_tav_1, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_1, 'w') as f:
    f.write(modified_json)
    

# Save df_tav_2 to JSON
df_tav_2.to_json(json_path_tav_2, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_2, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_2, 'w') as f:
    f.write(data)
    
with open(json_path_tav_2, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_2, 'w') as f:
    f.write(modified_json)
    

#Save df_tav_3 to JSON
df_tav_3.to_json(json_path_tav_3, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_3, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_3, 'w') as f:
    f.write(data)
    
with open(json_path_tav_3, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_3, 'w') as f:
    f.write(modified_json)

,"Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2012",Column2,Column3,Column4,Column5,Column6,Column7
0,PROVINCE E REGIONI,Biblioteche,Persone ammesse al prestito,Opere in prestito a privati,Opere in prestito a biblioteche,Opere ricevute in prestito da biblioteche,Opere consultate
1,Torino,2,5420,13551,663,281,65076
2,Piemonte,2,5420,13551,663,281,65076
3,Valle d'Aosta/Vall√©e d'Aoste,-,-,-,-,-,-
4,Cremona,1,1470,14318,752,833,386948
5,Milano,1,1414,9985,2462,258,16411
6,Pavia,1,2122,5588,500,225,16739
7,Lombardia,3,5006,29891,3714,1316,420098
8,Bolzano/Bozen,-,-,-,-,-,-
9,Trento,-,-,-,-,-,-
10,Trentino-Alto Adige,-,-,-,-,-,-
11,Padova,3,2688,7937,894,246,40802
12,Venezia,1,1172,5059,844,229,27680
13,Veneto,4,3860,12996,1738,475,68482
14,Gorizia,1,4733,14613,574,168,51372
15,Trieste,1,1565,5768,86,142,29945
16,Friuli-Venezia Giulia,2,6298,20381,660,310,81317
17,Genova,1,2540,5797,487,528,15520
18,Liguria,1,2540,5797,487,528,15520
19,Modena,1,2051,4031,545,147,12994
20,Parma,1,1504,3827,270,101,12230
21,Emilia-Romagna,2,3555,7858,815,248,25224
22,Firenze,4,3799,12070,1810,128,402184
23,Lucca,1,3174,1821,352,239,14250
24,Pisa,1,5122,290,96,67,11824
25,Toscana,6,12095,14181,2258,434,428258
26,Umbria,-,-,-,-,-,-
27,Macerata,1,3910,8831,159,20,22550
28,Marche,1,3910,8831,159,20,22550
29,Frosinone,3,-,-,-,-,49570
30,Rieti,1,16,45,-,-,686
31,Roma,11,35776,55253,2866,732,515190
32,Lazio,15,35792,55298,2866,732,565446
33,Abruzzo,-,-,-,-,-,-
34,Molise,-,-,-,-,-,-
35,Avellino,1,586,689,90,240,6775
36,Napoli,3,5039,9585,360,575,194127
37,Salerno,1,19,103,-,2,1515
38,Campania,5,5644,10377,451,817,202417
39,Bari,1,616,2028,345,51,7845
40,Puglia,1,616,2028,345,51,7845
41,Potenza,1,528,3329,216,105,19890
42,Basilicata,1,528,3329,216,105,19890
43,Cosenza,1,510,2592,382,248,4464
44,Calabria,1,510,2592,382,248,4464
45,Sicilia,-,-,-,-,-,-
46,Cagliari,1,4984,7376,476,458,45574
47,Sassari,1,2686,2127,272,124,1254
48,Sardegna,2,7670,9503,748,582,46828
49,,,,,,,
50,ITALIA,46,93444,196613,15502,5516,1973415
51,Nord,14,26679,90474,8077,3158,675717
52,Centro,22,51797,78310,5283,1186,1016254
53,Mezzogiorno,10,14968,27829,2142,1684,281444

,Tav. 2 - Biblioteche statali dipendenti dal MiBact per tipologia e provincia e consistenza del patrimonio librario - Anno 2012,Column3,Column4,Column5,Column6
0,PROVINCE E REGIONI,Volumi manoscritti,Volumi stampati,Opuscoli,Periodici
1,Torino,8979,966456,204558,1272
2,Piemonte,8979,966456,204558,1272
3,Valle d'Aosta/Vall√©e d'Aoste,-,-,-,-
4,Cremona,3879,477182,86561,45
5,Milano,2119,1023094,299669,2529
6,Pavia,1411,386774,119587,162
7,Lombardia,7409,1887050,505817,2736
8,Bolzano/Bozen,-,-,-,-
9,Trento,-,-,-,-
10,Trentino-Alto Adige,-,-,-,-
11,Padova,2946,609911,228946,762
12,Venezia,13118,635939,263115,531
13,Veneto,16064,1245850,492061,1293
14,Gorizia,900,357903,82031,482
15,Trieste,8,189763,19737,180
16,Friuli-Venezia Giulia,908,547666,101768,662
17,Genova,1949,402228,103444,1148
18,Liguria,1949,402228,103444,1148
19,Modena,11025,565925,129520,490
20,Parma,52244,677009,130942,208
21,Emilia-Romagna,63269,1242934,260462,698
22,Firenze,43438,6453328,2934301,20545
23,Lucca,4323,380040,88010,298
24,Pisa,1395,476631,105369,1915
25,Toscana,49156,7309999,3127680,22758
26,Umbria,-,-,-,-
27,Macerata,64,80135,4006,-
28,Marche,64,80135,4006,-
29,Frosinone,2680,177479,5370,103
30,Rieti,350,43968,2444,-
31,Roma,25402,6867355,2006919,34349
32,Lazio,28432,7088802,2014733,34452
33,Abruzzo,-,-,-,-
34,Molise,-,-,-,-
35,Avellino,580,156663,22623,144
36,Napoli,18566,2172952,....,1132
37,Salerno,438,85700,7149,69
38,Campania,19584,2415315,481238,1345
39,Bari,454,306858,65542,76
40,Puglia,454,306858,65542,76
41,Potenza,74,130728,11615,479
42,Basilicata,74,130728,11615,479
43,Cosenza,117,117841,14372,137
44,Calabria,117,117841,14372,137
45,Sicilia,-,-,-,-
46,Cagliari,604,544182,29952,801
47,Sassari,957,201760,25009,2706
48,Sardegna,1561,745942,54961,3507
49,,,,,
50,ITALIA,198020,24487804,7442257,70563
51,Nord,98578,6292184,1668110,7809
52,Centro,77652,14478936,5146419,57210
53,Mezzogiorno,21790,3716684,627728,5544

,"Tav. 3 - Biblioteche statali dipendenti dal MiBact, posti per lettori, lettori in totale e stranieri - Anno 2012",Column2,Column4,Column5
0,PROVINCE E REGIONI,Posti per lettori,Lettori in totale,Lettori Stranieri
1,Torino,416,149103,6733
2,Piemonte,416,149103,6733
3,Valle d'Aosta/Vall√©e d'Aoste,-,-,-
4,Cremona,220,134213,11215
5,Milano,240,49041,7356
6,Pavia,63,34307,1255
7,Lombardia,523,217561,19826
8,Bolzano/Bozen,-,-,-
9,Trento,-,-,-
10,Trentino-Alto Adige,-,-,-
11,Padova,252,54596,1105
12,Venezia,76,26830,1722
13,Veneto,328,81426,2827
14,Gorizia,102,47461,2038
15,Trieste,120,25500,3144
16,Friuli-Venezia Giulia,222,72961,5182
17,Genova,99,36167,7200
18,Liguria,99,36167,7200
19,Modena,220,16124,3162
20,Parma,142,21419,2150
21,Emilia-Romagna,362,37543,5312
22,Firenze,589,170747,24886
23,Lucca,80,10510,70
24,Pisa,120,24400,600
25,Toscana,789,205657,25556
26,Umbria,-,-,-
27,Macerata,104,21943,3657
28,Marche,104,21943,3657
29,Frosinone,64,10828,522
30,Rieti,40,365,6
31,Roma,1866,468564,24194
32,Lazio,1970,479757,24722
33,Abruzzo,-,-,-
34,Molise,-,-,-
35,Avellino,116,1742,6
36,Napoli,694,74868,1130
37,Salerno,18,734,38
38,Campania,828,77344,1174
39,Bari,230,25298,298
40,Puglia,230,25298,298
41,Potenza,313,52620,-
42,Basilicata,313,52620,-
43,Cosenza,65,9397,36
44,Calabria,65,9397,36
45,Sicilia,-,-,-
46,Cagliari,98,21174,2236
47,Sassari,140,6852,-
48,Sardegna,238,28026,2236
49,,,,
50,ITALIA,6487,1494803,104759
51,Nord,1950,594761,47080
52,Centro,2863,707357,53935
53,Mezzogiorno,1674,192685,3744

In [12]:
#Dataframes and JSON files of Biblioteche Mibact - Anno 2013

import pandas as pd
import json
from IPython.display import display

json_path=r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Biblio_Mibact_Statali_Ministero_2013.json"
with open(json_path, 'r', encoding='utf-8') as file:
    json_data = json.load(file)


# Rimuovere i valori null
cleaned_data = {key: [entry for entry in value if entry is not None] for key, value in json_data.items()}

# Convertire in DataFrame
df_tav_4_7 = pd.DataFrame(cleaned_data["Tav 4.7"])
df_tav_4_7 = df_tav_4_7.replace('\n', '', regex=True)
df_tav_4_7= df_tav_4_7.fillna(value='')
df_tav_4_8 = pd.DataFrame(cleaned_data["Tav 4.8"])
df_tav_4_8= df_tav_4_8.fillna(value='')
df_tav_4_9 = pd.DataFrame(cleaned_data["Tav 4.9"])
df_tav_4_9 = df_tav_4_9.replace('\n', ' ', regex=True)
df_tav_4_9= df_tav_4_9.fillna(value='')
df_tav_4_10 = pd.DataFrame(cleaned_data["Tav 4.10"])
df_tav_4_10 = df_tav_4_10.replace('\n', ' ', regex=True)
df_tav_4_10= df_tav_4_10.fillna(value='')
df_tav_4_10 = df_tav_4_10[['Column2', 'Column4', 'Column5', 'Column7']]
df_tav_4_10=df_tav_4_10.rename(columns={"Column2" : "Column3", 'Column7': 'Column6'})



#Rename columns
df_tav_1=df_tav_4_7.rename(columns={
    "Tavola 4.7 - Biblioteche, opere consultate, prestiti e personale delle biblioteche statali dipendenti dal Ministero dei beni e delle attivit√† culturali e del turismo per provincia - Anno 2013 ": 'Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2013' 
})
df_tav_1 = df_tav_1.drop(columns=['Column6', "Column5"])
df_tav_1=df_tav_1.rename(columns={"Column3" : "Column2", "Column4": "Column7"})
df_tav_1=pd.concat([df_tav_1, df_tav_4_10], axis=1)
ordered_columns = ['Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2013',  'Column2', 'Column3', 'Column4', 'Column5', 'Column6', 'Column7']
df_tav_1 = df_tav_1.reindex(columns=ordered_columns)
display(df_tav_1)

df_tav_2=df_tav_4_8.rename(columns={"Tavola 4.8 - Consistenza del patrimonio librario delle biblioteche statali dipendenti dal Ministero dei beni e delle attivit√† culturali e del turismo per tipologia e provincia - Anno 2013": 'Tav. 2 - Biblioteche statali dipendenti dal MiBact per tipologia e provincia  e consistenza del patrimonio librario - Anno 2013'})
display(df_tav_2)

df_tav_3 = df_tav_4_9.rename(columns={"Tavola 4.9 - Posti, lettori, lettori in totale e stranieri e opere consultate delle biblioteche statali dipendenti dal Ministero dei beni e delle attivit√† culturali e del turismo per provincia e regione - Anno 2013": "Tav. 3 - Biblioteche statali dipendenti dal MiBact, posti per lettori, lettori in totale e stranieri - Anno 2013"})
df_tav_3 = df_tav_3.drop(columns=['Column6'])
display(df_tav_3)



json_path_tav_1 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_1_prestiti_2013.json"
json_path_tav_2 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_2_patrimonio_2013.json"
json_path_tav_3 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_3_lettura_2013.json"



#Save df_tav_1 to JSON
df_tav_1.to_json(json_path_tav_1, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_1, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_1, 'w') as f:
    f.write(data)
    
with open(json_path_tav_1, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_1, 'w') as f:
    f.write(modified_json)
    

# Save df_tav_2 to JSON
df_tav_2.to_json(json_path_tav_2, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_2, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_2, 'w') as f:
    f.write(data)
    
with open(json_path_tav_2, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_2, 'w') as f:
    f.write(modified_json)
    

#Save df_tav_3 to JSON
df_tav_3.to_json(json_path_tav_3, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_3, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_3, 'w') as f:
    f.write(data)
    
with open(json_path_tav_3, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_3, 'w') as f:
    f.write(modified_json)

,"Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2013",Column2,Column3,Column4,Column5,Column6,Column7
0,PROVINCE E REGIONI,Biblioteche,Persone ammesse al prestito,Opere date in prestito a privati,,Opere ricevute in prestito da biblioteche,Opere consultate
1,Torino,2,4451,11449,805.0,402,45598
2,Piemonte,2,4451,11449,805.0,402,45598
3,Valle d'Aosta/Vall√©e d'Aoste,-,0,0,0.0,0,_
4,Genova,1,3233,5182,127.0,309,15211
5,Liguria,1,3233,5182,127.0,309,15211
6,Cremona,1,1618,11593,788.0,835,337809
7,Milano,1,1591,14100,2407.0,279,15832
8,Pavia,1,2182,4960,408.0,165,14455
9,Lombardia,3,5391,30653,3603.0,1279,368096
10,Bolzano/Bozen,-,-,0,0.0,0,_
11,Trento,-,-,0,0.0,0,_
12,Trentino-Alto Adige,-,-,0,0.0,0,_
13,Padova,3,2579,8029,878.0,236,40412
14,Venezia,1,704,5544,852.0,220,24600
15,Veneto,4,3283,13573,1730.0,456,65012
16,Gorizia,1,4759,15040,538.0,315,37007
17,Trieste,1,1806,5399,74.0,107,33350
18,Friuli-Venezia Giulia,2,6565,20439,612.0,422,70357
19,Modena,1,1909,4565,588.0,120,13268
20,Parma,1,1264,3279,218.0,96,18151
21,Emilia-Romagna,2,3173,7844,806.0,216,31419
22,Firenze,4,3372,10207,1034.0,52,348373
23,Lucca,1,3448,1824,475.0,286,14127
24,Pisa,1,5234,396,128.0,22,2302
25,Toscana,6,12054,12427,1637.0,360,364802
26,Umbria,-,,0,0.0,0,_
27,Macerata,1,1851,9407,118.0,50,19550
28,Marche,1,1851,9407,118.0,50,19550
29,Frosinone,3,0,0,0.0,0,34720
30,Rieti,1,18,51,0.0,0,690
31,Roma,11,35305,52114,2970.0,821,510342
32,Lazio,15,35323,52165,2970.0,821,545752
33,Abruzzo,-,-,0,0.0,0,_
34,Molise,-,-,0,0.0,0,_
35,Avellino,1,400,826,82.0,234,6048
36,Napoli,3,5379,11213,616.0,491,181188
37,Salerno,1,21,108,0.0,3,1049
38,Campania,5,5800,12147,698.0,728,188285
39,Bari,1,917,2138,387.0,101,7946
40,Puglia,1,917,2138,387.0,101,7946
41,Potenza,1,1223,3705,190.0,212,18673
42,Basilicata,1,1223,3705,190.0,212,18673
43,Cosenza,1,564,2447,310.0,325,4322
44,Calabria,1,564,2447,310.0,325,4322
45,Sicilia,-,-,0,0.0,0,_
46,Cagliari,1,4146,6220,434.0,311,48693
47,Sassari,1,2986,1051,242.0,146,1254
48,Sardegna,2,7132,7271,676.0,457,49947
49,,,,,,,
50,ITALIA,46,90960,190847,14669.0,6138,1794970
51,Nord,14,26096,89140,7683.0,3084,595693
52,Centro,22,49228,73999,4725.0,1231,930104
53,Mezzogiorno,10,15636,27708,2261.0,1823,269173

,Tav. 2 - Biblioteche statali dipendenti dal MiBact per tipologia e provincia e consistenza del patrimonio librario - Anno 2013,Column3,Column4,Column5,Column6
0,PROVINCE E REGIONI,Volumi manoscritti,Volumi stampati,Opuscoli,Periodici
1,Torino,8979,974529,205028,1521
2,Piemonte,8979,974529,205028,1521
3,Valle d'Aosta/Vall√©e d'Aoste,-,-,-,-
4,Genova,1949,407134,103638,1148
5,Liguria,1949,407134,103638,1148
6,Cremona,3879,478150,86601,24
7,Milano,2119,1038157,299669,2581
8,Pavia,1411,387821,119754,77
9,Lombardia,7409,1904128,506024,2682
10,Bolzano/Bozen,-,-,-,-
11,Trento,-,-,-,-
12,Trentino-Alto Adige,-,-,-,-
13,Padova,2949,612641,229907,667
14,Venezia,13118,637948,263342,474
15,Veneto,16067,1250589,493249,1141
16,Gorizia,901,357909,82033,398
17,Trieste,8,190498,19921,161
18,Friuli-Venezia Giulia,909,548407,101954,559
19,Modena,11025,567292,129711,410
20,Parma,52244,679764,130999,250
21,Emilia-Romagna,63269,1247056,260710,660
22,Firenze,43438,6504577,2937658,17161
23,Lucca,4323,380989,88140,298
24,Pisa,1395,478303,105555,446
25,Toscana,49156,7363869,3131353,17905
26,Umbria,-,-,-,-
27,Macerata,64,80636,4029,-
28,Marche,64,80636,4029,0
29,Frosinone,2680,177844,5401,107
30,Rieti,350,44134,2444,-
31,Roma,25481,6966235,2012477,33599
32,Lazio,28511,7188213,2020322,33706
33,Abruzzo,-,-,-,-
34,Molise,-,-,-,-
35,Avellino,580,157129,22703,144
36,Napoli,18594,2178265,452813,1139
37,Salerno,438,87351,7646,61
38,Campania,19612,2422745,483162,1344
39,Bari,454,310390,65578,346
40,Puglia,454,310390,65578,346
41,Potenza,74,133485,11723,496
42,Basilicata,74,133485,11723,496
43,Cosenza,117,121328,15268,130
44,Calabria,117,121328,15268,130
45,Sicilia,-,-,-,-
46,Cagliari,604,545113,29990,798
47,Sassari,957,202659,25273,2706
48,Sardegna,1561,747772,55263,3504
49,,,,,
50,ITALIA,198131,24700281,7457301,65142
51,Nord,98582,6331843,1670603,7711
52,Centro,77731,14632718,5155704,51611
53,Mezzogiorno,21818,3735720,630994,5820

,"Tav. 3 - Biblioteche statali dipendenti dal MiBact, posti per lettori, lettori in totale e stranieri - Anno 2013",Column2,Column4,Column5
0,PROVINCE E REGIONI,Posti per lettori,Lettori in totale,Lettori Stranieri
1,Torino,416,108000,4350
2,Piemonte,416,109501,4441
3,Valle d'Aosta/Vall√©e d'Aoste,0,0,0
4,Genova,140,33205,6000
5,Liguria,140,33205,6000
6,Cremona,220,116058,8640
7,Milano,240,53757,8062
8,Pavia,63,33586,994
9,Lombardia,523,203401,17696
10,Bolzano/Bozen,0,0,0
11,Trento,0,0,0
12,Trentino-Alto Adige,0,0,0
13,Padova,252,56435,909
14,Venezia,76,25000,1300
15,Veneto,328,81435,2209
16,Gorizia,102,34114,1316
17,Trieste,120,29365,3175
18,Friuli-Venezia Giulia,222,63479,4491
19,Modena,220,5799,126
20,Parma,142,5162,1217
21,Emilia-Romagna,362,10961,1343
22,Firenze,589,174085,25658
23,Lucca,80,10450,51
24,Pisa,120,1753,40
25,Toscana,789,186288,25749
26,Umbria,0,0,0
27,Macerata,104,18480,2940
28,Marche,104,18480,2940
29,Frosinone,69,8763,535
30,Rieti,40,370,7
31,Roma,1861,446732,20233
32,Lazio,1970,455865,20775
33,Abruzzo,0,0,0
34,Molise,0,0,0
35,Avellino,116,1361,2
36,Napoli,694,112199,1135
37,Salerno,18,538,17
38,Campania,828,114098,1154
39,Bari,230,30304,413
40,Puglia,230,30304,413
41,Potenza,313,50678,-
42,Basilicata,313,50678,0
43,Cosenza,65,10967,65
44,Calabria,65,10967,65
45,Sicilia,0,0,0
46,Cagliari,98,19205,2453
47,Sassari,140,6852,-
48,Sardegna,238,26057,2453
49,,,,
50,ITALIA,6528,1394719,89729
51,Nord,1991,501982,36180
52,Centro,2863,660633,49464
53,Mezzogiorno,1674,232104,4085

In [13]:
#Dataframes and JSON files of Biblioteche Mibact - Anno 2014

import pandas as pd
import json
from IPython.display import display

json_path=r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Biblio_Mibact_Statali_Ministero_2014.json"
with open(json_path, 'r', encoding='utf-8') as file:
    json_data = json.load(file)


# Rimuovere i valori null
cleaned_data = {key: [entry for entry in value if entry is not None] for key, value in json_data.items()}

# Convertire in DataFrame
df_tav_4_4 = pd.DataFrame(cleaned_data["Tav 4.4"])
df_tav_4_4= df_tav_4_4.replace('\n', '', regex=True)
df_tav_4_4= df_tav_4_4.fillna(value='')
df_tav_4_5 = pd.DataFrame(cleaned_data["Tav 4.5"])
df_tav_4_5= df_tav_4_5.fillna(value='')
df_tav_4_6 = pd.DataFrame(cleaned_data["Tav 4.6"])
df_tav_4_6= df_tav_4_6.replace('\n', ' ', regex=True)
df_tav_4_6= df_tav_4_6.fillna(value='')
df_tav_4_7= pd.DataFrame(cleaned_data["Tav 4.7"])
df_tav_4_7 = df_tav_4_7.replace('\n', ' ', regex=True)
df_tav_4_7= df_tav_4_7.fillna(value='')
df_tav_4_7 = df_tav_4_7[['Column2', 'Column4', 'Column5', 'Column7']]
df_tav_4_7=df_tav_4_7.rename(columns={"Column2" : "Column3", 'Column7': 'Column6'})



#Rename columns
df_tav_1=df_tav_4_4.rename(columns={
    "Tavola 4.4 - Biblioteche, opere consultate, prestiti e personale delle biblioteche statali dipendenti dal Ministero dei beni e delle attivit√† culturali e del turismo per provincia - Anno 2014": 'Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2014' 
})
df_tav_1 = df_tav_1.drop(columns=['Column6', "Column5"])
df_tav_1=df_tav_1.rename(columns={"Column3" : "Column2", "Column4": "Column7"})
df_tav_1=pd.concat([df_tav_1, df_tav_4_7], axis=1)
ordered_columns = ['Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2014',  'Column2', 'Column3', 'Column4', 'Column5', 'Column6', 'Column7']
df_tav_1 = df_tav_1.reindex(columns=ordered_columns)
display(df_tav_1)

df_tav_2=df_tav_4_5.rename(columns={"Tavola 4.5 - Consistenza del patrimonio librario delle biblioteche statali dipendenti dal Ministero dei beni e delle attivit√† culturali e del turismo per tipologia e provincia - Anno 2014": 'Tav. 2 - Biblioteche statali dipendenti dal MiBact per tipologia e provincia  e consistenza del patrimonio librario - Anno 2014'})
display(df_tav_2)

df_tav_3 = df_tav_4_6.rename(columns={"Tavola 4.6 - Posti, lettori, lettori in totale e stranieri e opere consultate delle biblioteche statali dipendenti dal Ministero dei beni e delle attivit√† culturali e del turismo per provincia e regione - Anno 2014": "Tav. 3 - Biblioteche statali dipendenti dal MiBact, posti per lettori, lettori in totale e stranieri - Anno 2014"})
df_tav_3 = df_tav_3.drop(columns=['Column6'])
display(df_tav_3)



json_path_tav_1 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_1_prestiti_2014.json"
json_path_tav_2 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_2_patrimonio_2014.json"
json_path_tav_3 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_3_lettura_2014.json"



#Save df_tav_1 to JSON
df_tav_1.to_json(json_path_tav_1, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_1, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_1, 'w') as f:
    f.write(data)
    
with open(json_path_tav_1, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_1, 'w') as f:
    f.write(modified_json)
    

# Save df_tav_2 to JSON
df_tav_2.to_json(json_path_tav_2, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_2, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_2, 'w') as f:
    f.write(data)
    
with open(json_path_tav_2, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_2, 'w') as f:
    f.write(modified_json)
    

#Save df_tav_3 to JSON
df_tav_3.to_json(json_path_tav_3, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_3, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_3, 'w') as f:
    f.write(data)
    
with open(json_path_tav_3, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_3, 'w') as f:
    f.write(modified_json)

,"Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2014",Column2,Column3,Column4,Column5,Column6,Column7
0,PROVINCE E REGIONI,Biblioteche,Persone ammesse al prestito,Opere date in prestito a privati,pere date in prestito a biblioteche,Opere ricevute in prestito da biblioteche,Opere consultate
1,Torino,2,4000,10970,479,238,36983
2,Piemonte,2,4000,10970,479,238,36983
3,Valle d'Aosta/Vall√©e d'Aoste,-,-,-,-,-,_
4,Genova,1,19961,4598,330,322,9015
5,Liguria,1,19961,4598,330,322,9015
6,Cremona,1,1918,12469,753,896,327031
7,Milano,1,3002,13376,2261,244,13639
8,Pavia,1,1967,4646,468,117,13062
9,Lombardia,3,6887,30491,3482,1257,353732
10,Bolzano/Bozen,-,-,-,-,-,_
11,Trento,-,-,-,-,-,_
12,Trentino-Alto Adige,-,-,-,-,-,_
13,Padova,3,1911,7105,737,144,40693
14,Venezia,1,682,5315,683,185,23571
15,Veneto,4,2593,12420,1420,329,64264
16,Gorizia,1,4616,11892,522,343,24080
17,Trieste,1,1931,5247,65,123,45821
18,Friuli-Venezia Giulia,2,6547,17139,587,466,69901
19,Modena,1,1647,4454,479,140,14036
20,Parma,1,11241,3223,183,144,17066
21,Emilia-Romagna,2,12888,7677,662,284,31102
22,Firenze,4,2977,9827,1028,77,245940
23,Lucca,1,2567,1501,349,134,7683
24,Pisa,1,5041,392,271,122,6761
25,Toscana,6,10585,11720,1648,333,260384
26,Umbria,-,,,,,_
27,Macerata,1,1818,9084,133,46,17450
28,Marche,1,1818,9084,133,46,17450
29,Frosinone,3,-,-,-,-,49580
30,Rieti,1,20,58,0,0,700
31,Roma,11,41586,51294,3095,606,512574
32,Lazio,15,41606,51352,3095,606,562854
33,Abruzzo,-,-,-,-,-,_
34,Molise,-,-,-,-,-,_
35,Avellino,1,162,921,87,239,6329
36,Napoli,3,5697,10196,575,407,223858
37,Salerno,1,25,96,0,0,1106
38,Campania,5,5884,11213,662,646,231293
39,Bari,1,2799,1970,316,68,13311
40,Puglia,1,2799,1970,316,68,13311
41,Potenza,1,1077,3412,220,231,22212
42,Basilicata,1,1077,3412,220,231,22212
43,Cosenza,1,588,2857,242,273,3739
44,Calabria,1,588,2857,242,273,3739
45,Sicilia,-,-,-,-,-,_
46,Cagliari,1,3540,5547,357,255,42655
47,Sassari,1,173,562,196,142,1327
48,Sardegna,2,3713,6109,553,397,43982
49,,,,,,,
50,Nord,14,52876,83295,6960,2896,564997
51,Centro,22,54009,72156,4876,985,840688
52,Mezzogiorno,10,14061,25561,1993,1615,314537
53,,,,,,,
54,Totale Italia,46,120946,181012,13829,5496,1720222

,Tav. 2 - Biblioteche statali dipendenti dal MiBact per tipologia e provincia e consistenza del patrimonio librario - Anno 2014,Column3,Column4,Column5,Column6
0,PROVINCE E REGIONI,Volumi manoscritti,Volumi stampati,Opuscoli,Periodici
1,Torino,8979,978590,205258,829
2,Piemonte,8979,978590,205258,829
3,Valle d'Aosta/Vall√©e d'Aoste,-,-,-,-
4,Genova,1949,416377,103673,2061
5,Liguria,1949,416377,103673,2061
6,Cremona,3879,479655,86701,28
7,Milano,2119,1050932,299669,2209
8,Pavia,1411,388901,119856,68
9,Lombardia,7409,1919488,506226,2305
10,Bolzano/Bozen,-,-,-,-
11,Trento,-,-,-,-
12,Trentino-Alto Adige,-,-,-,-
13,Padova,2951,614118,230321,368
14,Venezia,13118,637948,263342,504
15,Veneto,16069,1252066,493663,872
16,Gorizia,924,360344,82901,563
17,Trieste,8,192523,20100,138
18,Friuli-Venezia Giulia,932,552867,103001,701
19,Modena,11025,568727,129808,409
20,Parma,52244,681852,131099,143
21,Emilia-Romagna,63269,1250579,260907,552
22,Firenze,43490,6585516,2946033,21205
23,Lucca,4326,382160,88286,281
24,Pisa,1395,480497,105672,828
25,Toscana,49211,7448173,3139991,22314
26,Umbria,-,-,-,-
27,Macerata,64,81193,4044,-
28,Marche,64,81193,4044,0
29,Frosinone,2680,178204,5407,76
30,Rieti,350,44306,2444,-
31,Roma,25483,7033931,2013912,28426
32,Lazio,28513,7256441,2021763,28502
33,Abruzzo,-,-,-,-
34,Molise,-,-,-,-
35,Avellino,580,157530,22949,144
36,Napoli,18594,2181039,-,986
37,Salerno,438,87981,7725,48
38,Campania,19612,2426550,484029,1178
39,Bari,454,317252,65682,216
40,Puglia,454,317252,65682,216
41,Potenza,74,135337,11806,464
42,Basilicata,74,135337,11806,464
43,Cosenza,117,123131,15401,130
44,Calabria,117,123131,15401,130
45,Sicilia,-,-,-,-
46,Cagliari,604,546357,30039,789
47,Sassari,957,203318,26898,2917
48,Sardegna,1561,749675,56937,3706
49,,,,,
50,Nord,98607,6369967,1672728,7320
51,Centro,77788,14785807,5165798,50816
52,Mezzogiorno,21818,3751945,633855,5694
53,,,,,
54,Totale Italia,198213,24907719,7472381,63830

,"Tav. 3 - Biblioteche statali dipendenti dal MiBact, posti per lettori, lettori in totale e stranieri - Anno 2014",Column2,Column4,Column5
0,PROVINCE E REGIONI,Posti per lettori,Lettori in totale,Lettori Stranieri
1,Torino,319,108304,4304
2,Piemonte,319,108304,4304
3,Valle d'Aosta/Vall√©e d'Aoste,0,0,0
4,Genova,70,27000,3000
5,Liguria,70,27000,3000
6,Cremona,220,108968,7602
7,Milano,240,51540,7731
8,Pavia,63,32381,1079
9,Lombardia,523,192889,16412
10,Bolzano/Bozen,0,0,0
11,Trento,0,0,0
12,Trentino-Alto Adige,0,0,0
13,Padova,252,54312,705
14,Venezia,0,19898,1504
15,Veneto,252,74210,2209
16,Gorizia,102,27245,2350
17,Trieste,120,29484,1752
18,Friuli-Venezia Giulia,222,56729,4102
19,Modena,210,7767,362
20,Parma,142,16419,2578
21,Emilia-Romagna,352,24186,2940
22,Firenze,589,162210,28341
23,Lucca,80,10380,35
24,Pisa,120,3491,43
25,Toscana,789,176081,28419
26,Umbria,0,0,0
27,Macerata,104,16678,1550
28,Marche,104,16678,1550
29,Frosinone,69,8484,443
30,Rieti,40,375,8
31,Roma,1861,419094,16348
32,Lazio,1970,427953,16799
33,Abruzzo,0,0,0
34,Molise,0,0,0
35,Avellino,116,1445,14
36,Napoli,694,163083,2130
37,Salerno,18,608,40
38,Campania,828,165136,2184
39,Bari,230,31790,351
40,Puglia,230,31790,351
41,Potenza,-,44946,560
42,Basilicata,-,44946,560
43,Cosenza,65,9073,60
44,Calabria,65,9073,60
45,Sicilia,-,-,-
46,Cagliari,98,19674,2822
47,Sassari,85,6521,-
48,Sardegna,183,26195,2822
49,,,,
50,Nord,1738,483318,32967
51,Centro,2863,620712,46768
52,Mezzogiorno,1306,277140,5977
53,,,,
54,Totale Italia,5907,1381170,85712

In [14]:
#Dataframes and JSON files of Biblioteche Mibact - Anno 2015

import pandas as pd
import json
from IPython.display import display

json_path=r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Biblio_Mibact_Statali_Ministero_2015.json"
with open(json_path, 'r', encoding='utf-8') as file:
    json_data = json.load(file)


# Rimuovere i valori null
cleaned_data = {key: [entry for entry in value if entry is not None] for key, value in json_data.items()}

# Convertire in DataFrame
df_tav_4_4 = pd.DataFrame(cleaned_data["Tav. 4.4"])
df_tav_4_4= df_tav_4_4.replace('\n', '', regex=True)
df_tav_4_4= df_tav_4_4.fillna(value='')
df_tav_4_5 = pd.DataFrame(cleaned_data["Tav. 4.5"])
df_tav_4_5= df_tav_4_5.fillna(value='')
df_tav_4_6 = pd.DataFrame(cleaned_data["Tav. 4.6"])
df_tav_4_6= df_tav_4_6.replace('\n', ' ', regex=True)
df_tav_4_6= df_tav_4_6.fillna(value='')
df_tav_4_7= pd.DataFrame(cleaned_data["Tav. 4.7"])
df_tav_4_7 = df_tav_4_7.replace('\n', ' ', regex=True)
df_tav_4_7= df_tav_4_7.fillna(value='')
df_tav_4_7 = df_tav_4_7[['Column2', 'Column4', 'Column5', 'Column7']]
df_tav_4_7=df_tav_4_7.rename(columns={"Column2" : "Column3", 'Column7': 'Column6'})



#Rename columns
df_tav_1=df_tav_4_4.rename(columns={
    "Tavola 4.4 - Biblioteche, opere consultate, prestiti e personale delle biblioteche statali dipendenti dal Ministero dei beni e delle attivit√† culturali e del turismo per provincia - Anno 2015 ": 'Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2015' 
})
df_tav_1 = df_tav_1.drop(columns=['Column6', "Column5"])
df_tav_1=df_tav_1.rename(columns={"Column3" : "Column2", "Column4": "Column7"})
df_tav_1=pd.concat([df_tav_1, df_tav_4_7], axis=1)
ordered_columns = ['Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2015',  'Column2', 'Column3', 'Column4', 'Column5', 'Column6', 'Column7']
df_tav_1 = df_tav_1.reindex(columns=ordered_columns)
display(df_tav_1)

df_tav_2=df_tav_4_5.rename(columns={"Tavola 4.5 - Consistenza del patrimonio librario delle biblioteche statali dipendenti dal Ministero dei beni e delle attivit√† culturali e del turismo per tipologia e provincia - Anno 2015": 'Tav. 2 - Biblioteche statali dipendenti dal MiBact per tipologia e provincia  e consistenza del patrimonio librario - Anno 2015'})
display(df_tav_2)

df_tav_3 = df_tav_4_6.rename(columns={"Tavola 4.6 - Posti, lettori, lettori in totale e stranieri e opere consultate delle biblioteche statali dipendenti dal Ministero dei beni e delle attivit√† culturali e del turismo per provincia e regione - Anno 2015": "Tav. 3 - Biblioteche statali dipendenti dal MiBact, posti per lettori, lettori in totale e stranieri - Anno 2015"})
df_tav_3 = df_tav_3.drop(columns=['Column6'])
display(df_tav_3)



json_path_tav_1 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_1_prestiti_2015.json"
json_path_tav_2 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_2_patrimonio_2015.json"
json_path_tav_3 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_3_lettura_2015.json"



#Save df_tav_1 to JSON
df_tav_1.to_json(json_path_tav_1, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_1, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_1, 'w') as f:
    f.write(data)
    
with open(json_path_tav_1, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_1, 'w') as f:
    f.write(modified_json)
    

# Save df_tav_2 to JSON
df_tav_2.to_json(json_path_tav_2, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_2, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_2, 'w') as f:
    f.write(data)
    
with open(json_path_tav_2, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_2, 'w') as f:
    f.write(modified_json)
    

#Save df_tav_3 to JSON
df_tav_3.to_json(json_path_tav_3, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_3, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_3, 'w') as f:
    f.write(data)
    
with open(json_path_tav_3, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_3, 'w') as f:
    f.write(modified_json)

,"Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2015",Column2,Column3,Column4,Column5,Column6,Column7
0,PROVINCE E REGIONI,Biblioteche,Persone ammesse al prestito,Opere date in prestito a privati,Opere date in prestito a biblioteche,Opere ricevute in prestito da biblioteche,Opere consultate
1,Torino,2,3382,9231,465,241,30454
2,Piemonte,2,3382,9231,465,241,30454
3,Valle d'Aosta/Vall√©e d'Aoste,-,-,-,-,-,-
4,Genova,1,20414,3253,249,488,5973
5,Liguria,1,20414,3253,249,488,5973
6,Cremona,1,1715,11278,713,666,234202
7,Milano,1,4027,12620,2401,175,13213
8,Pavia,1,1966,4702,375,137,13062
9,Lombardia,3,7708,28600,3489,978,260477
10,Bolzano/Bozen,-,-,-,-,-,-
11,Trento,-,-,-,-,-,-
12,Trentino-Alto Adige,-,-,-,-,-,-
13,Padova,3,2291,6557,753,157,36990
14,Venezia,1,780,4769,743,137,25803
15,Veneto,4,3071,11326,1496,294,62793
16,Gorizia,1,5195,16759,549,521,23446
17,Trieste,1,1762,5994,82,51,43128
18,Friuli-Venezia Giulia,2,6957,22753,631,572,66574
19,Modena,1,1593,4286,459,175,15618
20,Parma,1,12043,2732,151,162,9865
21,Emilia-Romagna,2,13636,7018,610,337,25483
22,Firenze,4,2526,8687,2193,90,211552
23,Lucca,1,2684,1445,442,240,8257
24,Pisa,1,6114,514,281,121,11386
25,Toscana,6,11324,10646,2916,451,231195
26,Umbria,-,-,-,-,-,-
27,Macerata,1,1808,9595,104,34,16775
28,Marche,1,1808,9595,104,34,16775
29,Frosinone,3,-,0,0,0,38865
30,Rieti,1,21,60,0,0,700
31,Roma,11,43853,52133,3521,582,437492
32,Lazio,15,43874,52193,3521,582,477057
33,Abruzzo,-,-,-,-,-,-
34,Molise,-,-,-,-,-,-
35,Avellino,1,616,880,45,164,6067
36,Napoli,3,5561,7986,529,400,216169
37,Salerno,1,23,83,0,2,1211
38,Campania,5,6200,8949,574,566,223447
39,Bari,1,3303,1980,382,80,15520
40,Puglia,1,3303,1980,382,80,15520
41,Potenza,1,915,3600,198,170,17653
42,Basilicata,1,915,3600,198,170,17653
43,Cosenza,1,427,2340,203,352,21485
44,Calabria,1,427,2340,203,352,21485
45,Sicilia,-,-,-,-,-,-
46,Cagliari,1,3255,4469,304,203,42334
47,Sassari,1,163,487,204,109,1392
48,Sardegna,2,3418,4956,508,312,43726
49,,,,,,,
50,Nord,14,55168,82181,6940,2910,451754
51,Centro,22,57006,72434,6541,1067,725027
52,Mezzogiorno,10,14263,21825,1865,1480,321831
53,,,,,,,
54,Totale Italia,46,126437,176440,15346,5457,1498612

,Tav. 2 - Biblioteche statali dipendenti dal MiBact per tipologia e provincia e consistenza del patrimonio librario - Anno 2015,Column3,Column4,Column5,Column6
0,PROVINCE E REGIONI,Volumi manoscritti,Volumi stampati,Opuscoli,Periodici
1,Torino,8979,985363,205452,747
2,Piemonte,8979,985363,205452,747
3,Valle d'Aosta/Vall√©e d'Aoste,-,-,-,-
4,Genova,1949,420457,103752,-
5,Liguria,1949,420457,103752,0
6,Cremona,3879,481510,86768,12
7,Milano,2119,1072000,299669,2253
8,Pavia,1411,388901,119999,71
9,Lombardia,7409,1942411,506436,2336
10,Bolzano/Bozen,-,-,-,-
11,Trento,-,-,-,-
12,Trentino-Alto Adige,-,-,-,-
13,Padova,2953,616934,230648,1040
14,Venezia,13119,640177,263703,379
15,Veneto,16072,1257111,494351,1419
16,Gorizia,924,362913,83807,411
17,Trieste,8,190203,20429,167
18,Friuli-Venezia Giulia,932,553116,104236,578
19,Modena,11025,569639,129941,374
20,Parma,52244,684381,131247,139
21,Emilia-Romagna,63269,1254020,261188,513
22,Firenze,43492,6629298,2954183,10154
23,Lucca,4326,382790,88351,203
24,Pisa,1395,484105,105911,701
25,Toscana,49213,7496193,3148445,11058
26,Umbria,-,-,-,-
27,Macerata,64,81761,4053,-
28,Marche,64,81761,4053,0
29,Frosinone,2680,178546,5407,38
30,Rieti,350,44495,2444,-
31,Roma,25486,7103383,2016416,27648
32,Lazio,28516,7326424,2024267,27686
33,Abruzzo,-,-,-,-
34,Molise,-,-,-,-
35,Avellino,580,158098,23266,22
36,Napoli,18594,2183754,453973,938
37,Salerno,438,91502,8082,55
38,Campania,19612,2433354,485321,1015
39,Bari,454,323168,65762,80
40,Puglia,454,323168,65762,80
41,Potenza,74,136581,12002,-
42,Basilicata,74,136581,12002,0
43,Cosenza,119,125788,15559,133
44,Calabria,119,125788,15559,133
45,Sicilia,-,-,-,-
46,Cagliari,604,547235,30224,699
47,Sassari,2374,214799,26898,2963
48,Sardegna,2978,762034,57122,3662
49,,,,,
50,Nord,98610,6412478,1675415,5593
51,Centro,77793,14904378,5176765,38744
52,Mezzogiorno,23237,3780925,635766,4890
53,,,,,
54,Totale Italia,199640,25097781,7487946,49227

,"Tav. 3 - Biblioteche statali dipendenti dal MiBact, posti per lettori, lettori in totale e stranieri - Anno 2015",Column2,Column4,Column5
0,PROVINCE E REGIONI,Posti per lettori,Lettori in totale,Lettori Stranieri
1,Torino,319,104937,3848
2,Piemonte,319,104937,3848
3,Valle d'Aosta/Vall√©e d'Aoste,0,0,0
4,Genova,70,19499,9748
5,Liguria,70,19499,9748
6,Cremona,220,95683,5709
7,Milano,240,48106,3250
8,Pavia,63,29058,1257
9,Lombardia,523,172847,10216
10,Bolzano/Bozen,0,0,0
11,Trento,0,0,0
12,Trentino-Alto Adige,0,0,0
13,Padova,252,46436,615
14,Venezia,76,19711,1350
15,Veneto,328,66147,1965
16,Gorizia,102,24998,2711
17,Trieste,120,20153,597
18,Friuli-Venezia Giulia,222,45151,3308
19,Modena,210,10684,581
20,Parma,142,20576,-
21,Emilia-Romagna,352,31260,581
22,Firenze,589,155550,23461
23,Lucca,80,10168,27
24,Pisa,120,3518,68
25,Toscana,789,169236,23556
26,Umbria,0,0,0
27,Macerata,104,16072,482
28,Marche,104,16072,482
29,Frosinone,69,7330,367
30,Rieti,40,380,9
31,Roma,1817,368639,23831
32,Lazio,1926,376349,24207
33,Abruzzo,0,0,0
34,Molise,0,0,0
35,Avellino,116,1405,8
36,Napoli,683,396525,2540
37,Salerno,18,465,27
38,Campania,817,398395,2575
39,Bari,230,41218,720
40,Puglia,230,41218,720
41,Potenza,-,35306,350
42,Basilicata,-,35306,350
43,Cosenza,65,6751,55
44,Calabria,65,6751,55
45,Sicilia,-,-,-
46,Cagliari,98,17401,3335
47,Sassari,85,10616,-
48,Sardegna,183,28017,3335
49,,,,
50,Nord,1784,439841,29666
51,Centro,2819,561657,48245
52,Mezzogiorno,1295,509687,7035
53,,,,
54,Totale Italia,5898,1511185,84946

In [15]:
#Dataframes and JSON files of Biblioteche Mibact - Anno 2016

import pandas as pd
import json
from IPython.display import display

json_path=r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Biblio_Mibact_Statali_Ministero_2016.json"
with open(json_path, 'r', encoding='utf-8') as file:
    json_data = json.load(file)


# Rimuovere i valori null
cleaned_data = {key: [entry for entry in value if entry is not None] for key, value in json_data.items()}

# Convertire in DataFrame
df_tav_4_4 = pd.DataFrame(cleaned_data["Tav. 4.4"])
df_tav_4_4= df_tav_4_4.replace('\n', '', regex=True)
df_tav_4_4= df_tav_4_4.fillna(value='')
df_tav_4_5 = pd.DataFrame(cleaned_data["Tav. 4.5"])
df_tav_4_5= df_tav_4_5.fillna(value='')
df_tav_4_6 = pd.DataFrame(cleaned_data["Tav. 4.6"])
df_tav_4_6= df_tav_4_6.replace('\n', ' ', regex=True)
df_tav_4_6= df_tav_4_6.fillna(value='')
df_tav_4_7= pd.DataFrame(cleaned_data["Tav. 4.7"])
df_tav_4_7 = df_tav_4_7.replace('\n', ' ', regex=True)
df_tav_4_7= df_tav_4_7.fillna(value='')
df_tav_4_7 = df_tav_4_7[['Column2', 'Column4', 'Column5', 'Column7']]
df_tav_4_7=df_tav_4_7.rename(columns={"Column2" : "Column3", 'Column7': 'Column6'})



#Rename columns
df_tav_1=df_tav_4_4.rename(columns={
    "Tavola 4.4 - Biblioteche, opere consultate, prestiti e personale delle biblioteche statali dipendenti dal Ministero dei beni e delle attivit√† culturali e del turismo per provincia - Anno 2016": 'Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2016'  
})
df_tav_1 = df_tav_1.drop(columns=['Column6', "Column5"])
df_tav_1=df_tav_1.rename(columns={"Column3" : "Column2", "Column4": "Column7"})
df_tav_1=pd.concat([df_tav_1, df_tav_4_7], axis=1)
ordered_columns = ['Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2016',  'Column2', 'Column3', 'Column4', 'Column5', 'Column6', 'Column7']
df_tav_1 = df_tav_1.reindex(columns=ordered_columns)
display(df_tav_1)

df_tav_2=df_tav_4_5.rename(columns={"Tavola 4.5 - Consistenza del patrimonio librario delle biblioteche statali dipendenti dal Ministero dei beni e delle attivit√† culturali e del turismo per tipologia e provincia - Anno 2016": 'Tav. 2 - Biblioteche statali dipendenti dal MiBact per tipologia e provincia  e consistenza del patrimonio librario - Anno 2016'})
display(df_tav_2)

df_tav_3 = df_tav_4_6.rename(columns={"Tavola 4.6 - Posti, lettori, lettori in totale e stranieri e opere consultate delle biblioteche statali dipendenti dal Ministero dei beni e delle attivit√† culturali e del turismo per provincia e regione - Anno 2016": "Tav. 3 - Biblioteche statali dipendenti dal MiBact, posti per lettori, lettori in totale e stranieri - Anno 2016"})
df_tav_3 = df_tav_3.drop(columns=['Column6'])
display(df_tav_3)



json_path_tav_1 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_1_prestiti_2016.json"
json_path_tav_2 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_2_patrimonio_2016.json"
json_path_tav_3 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_3_lettura_2016.json"



#Save df_tav_1 to JSON
df_tav_1.to_json(json_path_tav_1, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_1, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_1, 'w') as f:
    f.write(data)
    
with open(json_path_tav_1, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_1, 'w') as f:
    f.write(modified_json)
    

# Save df_tav_2 to JSON
df_tav_2.to_json(json_path_tav_2, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_2, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_2, 'w') as f:
    f.write(data)
    
with open(json_path_tav_2, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_2, 'w') as f:
    f.write(modified_json)
    

#Save df_tav_3 to JSON
df_tav_3.to_json(json_path_tav_3, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_3, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_3, 'w') as f:
    f.write(data)
    
with open(json_path_tav_3, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_3, 'w') as f:
    f.write(modified_json)

,"Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anno 2016",Column2,Column3,Column4,Column5,Column6,Column7
0,PROVINCE E REGIONI,Biblioteche,Persone ammesse al prestito,Opere date in prestito a privati,Opere date in prestito abiblioteche,Opere ricevute in prestito da biblioteche,Opere consultate
1,Torino,2,2369,6342,343,167,23737
2,Piemonte,2,2369,6342,343,167,23737
3,Valle d'Aosta/Vall√©e d'Aoste,-,0,0,0,0,-
4,Genova,1,20837,3520,199,224,6802
5,Liguria,1,20837,3520,199,224,6802
6,Cremona,1,1557,9463,625,680,275638
7,Milano,1,4026,13364,2503,236,11895
8,Pavia,1,2060,4758,389,141,10783
9,Lombardia,3,7643,27585,3517,1057,298316
10,Bolzano/Bozen,-,0,0,0,0,-
11,Trento,-,0,0,0,0,-
12,Trentino-Alto Adige,-,0,0,0,0,-
13,Padova,3,2645,6285,749,149,35288
14,Venezia,1,809,4682,749,94,24900
15,Veneto,4,3454,10967,1498,243,60188
16,Gorizia,1,5034,11993,589,409,24903
17,Trieste,1,1749,6306,40,68,40089
18,Friuli-Venezia Giulia,2,6783,18299,629,477,64992
19,Modena,1,1532,4301,497,183,13689
20,Parma,1,973,2688,107,89,10532
21,Emilia-Romagna,2,2505,6989,604,272,24221
22,Firenze,4,2843,10381,2099,106,129462
23,Lucca,1,2886,1225,452,191,8900
24,Pisa,1,6200,497,197,75,14092
25,Toscana,6,11929,12103,2748,372,152454
26,Umbria,-,0,0,0,0,
27,Macerata,1,1793,8922,112,95,13460
28,Marche,1,1793,8922,112,95,13460
29,Frosinone,3,0,0,0,0,35525
30,Rieti,1,20,35,0,-,750
31,Roma,11,29187,42336,3879,376,372431
32,Lazio,15,29207,42371,3879,376,408706
33,Abruzzo,-,0,0,0,0,-
34,Molise,-,0,0,0,0,-
35,Avellino,1,99,329,48,126,4653
36,Napoli,3,6306,8271,528,441,147173
37,Salerno,1,9,65,0,-,1220
38,Campania,5,6414,8665,576,567,153046
39,Bari,1,1086,1923,206,37,5372
40,Puglia,1,1086,1923,206,37,5372
41,Potenza,1,838,3472,161,295,25831
42,Basilicata,1,838,3472,161,295,25831
43,Cosenza,1,374,2063,229,335,23293
44,Calabria,1,374,2063,229,335,23293
45,Sicilia,-,0,0,0,0,-
46,Cagliari,1,3736,4865,350,249,41011
47,Sassari,1,611,471,160,79,1165
48,Sardegna,2,4347,5336,510,328,42176
49,,,,,,,
50,Nord,14,43591,73702,6790,2440,478256
51,Centro,22,42929,63396,6739,843,574620
52,Mezzogiorno,10,13059,21459,1682,1562,249718
53,,,,,,,
54,Totale Italia,46,99579,158557,15211,4845,1302594

,Tav. 2 - Biblioteche statali dipendenti dal MiBact per tipologia e provincia e consistenza del patrimonio librario - Anno 2016,Column3,Column4,Column5,Column6
0,PROVINCE E REGIONI,Volumi manoscritti,Volumi stampati,Opuscoli,Periodici
1,Torino,8982,993274,206304,951
2,Piemonte,8982,993274,206304,951
3,Valle d'Aosta/Vall√©e d'Aoste,0,0,0,0
4,Genova,1949,427994,104089,-
5,Liguria,1949,427994,104089,0
6,Cremona,3880,483695,86888,17
7,Milano,2119,1089515,299669,1974
8,Pavia,1411,392203,120082,71
9,Lombardia,7410,1965413,506639,2062
10,Bolzano/Bozen,0,0,0,0
11,Trento,0,0,0,0
12,Trentino-Alto Adige,0,0,0,0
13,Padova,2958,620139,231017,378
14,Venezia,13119,641408,264634,403
15,Veneto,16077,1261547,495651,781
16,Gorizia,926,365460,84730,565
17,Trieste,8,190747,20806,142
18,Friuli-Venezia Giulia,934,556207,105536,707
19,Modena,11025,570630,130140,320
20,Parma,52244,685881,131307,139
21,Emilia-Romagna,63269,1256511,261447,459
22,Firenze,43492,6685662,2959492,14673
23,Lucca,4326,383555,88454,160
24,Pisa,1395,487607,106161,-
25,Toscana,49213,7556824,3154107,14833
26,Umbria,,,,
27,Macerata,64,82206,4055,-
28,Marche,64,82206,4055,0
29,Frosinone,2680,178774,5413,19
30,Rieti,350,44614,2444,-
31,Roma,25491,7177771,2017644,23788
32,Lazio,28521,7401159,2025501,23807
33,Abruzzo,0,0,0,0
34,Molise,0,0,0,0
35,Avellino,580,158499,23330,22
36,Napoli,18594,2187954,454610,971
37,Salerno,439,91840,8190,37
38,Campania,19613,2438293,486130,1030
39,Bari,454,326031,65802,170
40,Puglia,454,326031,65802,170
41,Potenza,74,139803,12185,264
42,Basilicata,74,139803,12185,264
43,Cosenza,119,131059,15960,132
44,Calabria,119,131059,15960,132
45,Sicilia,0,0,0,0
46,Cagliari,604,547767,30256,699
47,Sassari,2374,217304,26898,2963
48,Sardegna,2978,765071,57154,3662
49,,,,,
50,Nord,98621,6460946,1679666,4960
51,Centro,77798,15040189,5183663,38640
52,Mezzogiorno,23238,3800257,637231,5258
53,,,,,
54,Totale Italia,199657,25301392,7500560,48858

,"Tav. 3 - Biblioteche statali dipendenti dal MiBact, posti per lettori, lettori in totale e stranieri - Anno 2016",Column2,Column4,Column5
0,PROVINCE E REGIONI,Posti per lettori,Lettori in totale,Lettori Stranieri
1,Torino,324,55807,1979
2,Piemonte,324,55807,1979
3,Valle d'Aosta/Vall√©e d'Aoste,-,-,-
4,Genova,40,21905,10953
5,Liguria,40,21905,10953
6,Cremona,220,91490,3712
7,Milano,240,46427,2320
8,Pavia,63,31970,1620
9,Lombardia,523,169887,7652
10,Bolzano/Bozen,-,-,-
11,Trento,-,-,-
12,Trentino-Alto Adige,-,-,-
13,Padova,252,39349,161
14,Venezia,76,22232,1236
15,Veneto,328,61581,1397
16,Gorizia,102,28807,4360
17,Trieste,120,25387,219
18,Friuli-Venezia Giulia,222,54194,4579
19,Modena,210,11273,529
20,Parma,142,16985,1690
21,Emilia-Romagna,352,28258,2219
22,Firenze,589,127603,18743
23,Lucca,80,10583,28
24,Pisa,120,2968,51
25,Toscana,789,141154,18822
26,Umbria,,,
27,Macerata,104,14671,750
28,Marche,104,14671,750
29,Frosinone,69,6095,313
30,Rieti,40,380,10
31,Roma,1867,333013,25173
32,Lazio,1976,339488,25496
33,Abruzzo,-,-,-
34,Molise,-,-,-
35,Avellino,15,1176,2
36,Napoli,683,290459,2500
37,Salerno,18,505,43
38,Campania,716,292140,2545
39,Bari,230,23502,378
40,Puglia,230,23502,378
41,Potenza,313,32513,-
42,Basilicata,313,32513,0
43,Cosenza,65,6722,53
44,Calabria,65,6722,53
45,Sicilia,-,-,-
46,Cagliari,98,17408,3718
47,Sassari,85,9928,-
48,Sardegna,183,27336,3718
49,,,,
50,Nord,1789,391632,28779
51,Centro,2869,495313,45068
52,Mezzogiorno,1507,382213,6694
53,,,,
54,Totale Italia,6165,1269158,80541

In [16]:
#Dataframes and JSON files of Biblioteche Mibact - Anni 2017 - 2018

import pandas as pd
import json
from IPython.display import display

json_path=r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Biblio_Mibact_Statali_Ministero_2017-2018.json"
with open(json_path, 'r', encoding='utf-8') as file:
    json_data = json.load(file)


# Rimuovere i valori null
cleaned_data = {key: [entry for entry in value if entry is not None] for key, value in json_data.items()}

# Convertire in DataFrame
df_tav_4_1 = pd.DataFrame(cleaned_data["Tav. 4.1"])
df_tav_4_1= df_tav_4_1.replace('\n', '', regex=True)
df_tav_4_1= df_tav_4_1.fillna(value='')
df_tav_4_2 = pd.DataFrame(cleaned_data["Tav. 4.2"])
df_tav_4_2= df_tav_4_2.fillna(value='')
df_tav_4_3 = pd.DataFrame(cleaned_data["Tav. 4.3"])
df_tav_4_3= df_tav_4_3.replace('\n', ' ', regex=True)
df_tav_4_3= df_tav_4_3.fillna(value='')
df_tav_4_4= pd.DataFrame(cleaned_data["Tav. 4.4"])
df_tav_4_4 = df_tav_4_4.replace('\n', ' ', regex=True)
df_tav_4_4= df_tav_4_4.fillna(value='')
df_tav_4_4 = df_tav_4_4[['Column2',	'Column4','Column5','Column7','Column9', 'Column11', 'Column12','Column14']]
df_tav_4_4=df_tav_4_4.rename(columns={"Column2" : "Column3", 'Column7': 'Column6'})




#Rename columns
df_tav_1=df_tav_4_1.rename(columns={
    "Tavola 4.1 - Biblioteche, opere consultate, prestiti e personale delle biblioteche statali dipendenti dal Ministero dei beni e delle attivit√† culturali e del turismo per provincia - Anni 2017 e 2018": "Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anni 2017-2018"  
})
df_tav_1 = df_tav_1.drop(columns=['Column5', "Column6", 'Column10', 'Column11'])
df_tav_1=df_tav_1.rename(columns={"Column3" : "Column2", "Column4": "Column7", "Column9": 'Column15'})
df_tav_1=pd.concat([df_tav_1, df_tav_4_4], axis=1)
ordered_columns = ['Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anni 2017-2018',  'Column2', 'Column3', 'Column4', 'Column5', 'Column6', 'Column7', 'Column8', 'Column9', 'Column11','Column12','Column14','Column15']
df_tav_1 = df_tav_1.reindex(columns=ordered_columns)

#Removing duplicates strings
for year_2017 in df_tav_1["Column3"]:
    if year_2017 =="ANNO 2017":
        df_tav_1["Column3"] = df_tav_1["Column3"].replace("ANNO 2017", "")
        
for year_2017 in df_tav_1["Column9"]:
    if year_2017 =="ANNO 2018":
        df_tav_1["Column9"] = df_tav_1["Column9"].replace("ANNO 2018", "")      
display(df_tav_1)



df_tav_2=df_tav_4_2.rename(columns={ "Tavola 4.2 - Consistenza del patrimonio librario delle biblioteche statali dipendenti dal Ministero dei beni e delle attivit√† culturali e del turismo per tipologia e provincia - Anni  2017 e 2018": 'Tav. 2 - Biblioteche statali dipendenti dal MiBact per tipologia e provincia  e consistenza del patrimonio librario - Anni 2017-2018'})
display(df_tav_2)

df_tav_3 = df_tav_4_3.rename(columns={"Tavola 4.3 - Posti, lettori, lettori in totale e stranieri e opere consultate delle biblioteche statali dipendenti dal Ministero dei beni e delle attivit√† culturali e del turismo per provincia e regione - Anni 2017 e 2018": "Tav. 3 - Biblioteche statali dipendenti dal MiBact, posti per lettori, lettori in totale e stranieri - Anni 2017 e 2018"})
df_tav_3 = df_tav_3.drop(columns=['Column6','Column12'])
display(df_tav_3)



json_path_tav_1 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_1_prestiti_2017_2018.json"
json_path_tav_2 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_2_patrimonio_2017_2018.json"
json_path_tav_3 = r"C:\Users\HWRUser\Desktop\DHDK Course\Information Visualization\Data_Italian_publishers\Dati_biblioteche\Data_Biblioteche_Json\df_tav_3_lettura_2017_2018.json"



#Save df_tav_1 to JSON
df_tav_1.to_json(json_path_tav_1, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_1, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_1, 'w') as f:
    f.write(data)
    
with open(json_path_tav_1, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_1, 'w') as f:
    f.write(modified_json)
    

# Save df_tav_2 to JSON
df_tav_2.to_json(json_path_tav_2, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_2, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_2, 'w') as f:
    f.write(data)
    
with open(json_path_tav_2, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_2, 'w') as f:
    f.write(modified_json)
    

#Save df_tav_3 to JSON
df_tav_3.to_json(json_path_tav_3, orient='records', lines=True, force_ascii=False, indent=4)
# After exporting JSON
with open(json_path_tav_3, 'r') as f:
    data = f.read()

# Add square brackets
data = '[' + data.strip() + ']'

# Write back to the JSON file
with open(json_path_tav_3, 'w') as f:
    f.write(data)
    
with open(json_path_tav_3, 'r') as f:
    data = f.readlines()

# Join all lines to form a single string
json_content = ''.join(data)

# Split by '} ' to add commas
modified_json = json_content.replace('}\n', '},\n')  # Add comma after every '}'

# Write back to the JSON file
with open(json_path_tav_3, 'w') as f:
    f.write(modified_json)

,"Tav. 1 - Numero di Biblioteche statali dipendenti dal MiBact per regioni e provincie, opere consultate e prestiti a privati e altre biblioteche - Anni 2017-2018",Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column11,Column12,Column14,Column15
0,PROVINCE E REGIONI,Biblioteche,Persone ammesse al prestito,Opere in prestito a privati,Opere in prestito a biblioteche,Opere ricevute in prestito da biblioteche,Opere consultate,Biblioteche,Persone ammesse al prestito,Opere in prestito a privati,Opere in prestito a biblioteche,Opere ricevute in prestito da biblioteche,Opere consultate
1,,ANNO 2017,,,,,,ANNO 2018,,,,,
2,Torino,2,1950,4825,293,149,27250,2,1730,4331,320,147,22765
3,Piemonte,2,1950,4825,293,149,27250,2,1730,4331,320,147,22765
4,Valle d'Aosta/Vall√©e d'Aoste,-,-,-,-,-,-,-,-,-,0,0,-
5,Genova,1,20873,3520,199,224,3282,1,21725,4538,160,220,4163
6,Liguria,1,20873,3520,199,224,3282,1,21725,4538,160,220,4163
7,Cremona,1,1039,7758,773,1144,262043,1,1020,6719,587,1174,287119
8,Milano,1,2970,12213,1676,176,11570,1,3798,12162,1545,140,11912
9,Pavia,1,1925,4267,356,148,15712,1,1985,4302,348,125,23034
10,Lombardia,3,5934,24238,2805,1468,289325,3,6803,23183,2480,1439,322065
11,Bolzano/Bozen,-,-,0,0,0,-,-,-,-,-,-,-
12,Trento,-,-,0,0,0,-,-,-,-,-,-,-
13,Trentino-Alto Adige,-,-,0,0,0,-,-,-,-,-,-,-
14,Padova,3,2682,6412,629,169,16945,3,2803,5799,623,206,16453
15,Venezia,1,565,3897,585,113,24398,1,316,3333,507,55,23498
16,Veneto,4,3247,10309,1214,282,41343,4,3119,9132,1130,261,39951
17,Gorizia,1,3842,13985,824,487,25085,1,3253,11880,598,424,23874
18,Trieste,1,1785,7136,40,69,46161,1,1577,8547,44,70,54586
19,Friuli-Venezia Giulia,2,5627,21121,864,556,71246,2,4830,20427,642,494,78460
20,Modena,1,1426,4225,340,141,12494,1,1309,3737,316,128,13884
21,Parma,1,824,2440,92,98,10835,1,925,2088,88,20,8664
22,Emilia-Romagna,2,2250,6665,432,239,23329,2,2234,5825,404,148,22548
23,Firenze,4,2903,10614,1994,69,128592,4,3087,10974,2512,39,127830
24,Lucca,1,2945,1016,396,100,6242,1,4494,1268,374,144,5279
25,Pisa,1,6458,163,133,12,15936,1,7240,203,186,60,15900
26,Toscana,6,12306,11793,2523,181,150770,6,14821,12445,3072,243,149009
27,Umbria,-,-,0,0,0,-,-,,,,,-
28,Macerata,1,1404,8299,84,154,11025,1,1557,7410,58,129,9500
29,Marche,1,1404,8299,84,154,11025,1,1557,7410,58,129,9500
30,Frosinone,3,-,0,0,0,45713,3,0,0,0,0,36706
31,Rieti,1,4,20,0,0,740,1,4,27,0,0,755
32,Roma,11,29378,37989,3628,354,394946,11,38190,36717,3677,558,363968
33,Lazio,15,29382,38009,3628,354,441399,15,38194,36744,3677,558,401429
34,Abruzzo,-,-,0,0,0,-,-,-,-,-,-,-
35,Molise,-,-,0,0,0,-,-,-,-,-,-,-
36,Avellino,1,251,827,34,96,2174,1,118,626,41,83,2517
37,Napoli,3,5003,7291,502,296,99743,3,4326,6177,860,606,108906
38,Salerno,1,60,64,0,0,1202,1,60,73,0,0,1144
39,Campania,5,5314,8182,536,392,103119,5,4504,6876,901,689,112567
40,Bari,1,1445,1740,51,45,5498,1,265,1900,81,41,4250
41,Puglia,1,1445,1740,51,45,5498,1,265,1900,81,41,4250
42,Potenza,1,740,2888,135,190,17431,1,1348,2761,119,163,16775
43,Basilicata,1,740,2888,135,190,17431,1,1348,2761,119,163,16775
44,Cosenza,1,367,2088,193,377,32037,1,321,2195,169,228,33760
45,Calabria,1,367,2088,193,377,32037,1,321,2195,169,228,33760
46,Sicilia,-,-,0,0,0,-,-,,,,,-
47,Cagliari,1,2380,4428,259,189,46550,1,2068,4021,292,106,39573
48,Sassari,1,190,692,188,59,1181,1,205,499,226,83,1106
49,Sardegna,2,2570,5120,447,248,47731,2,2273,4520,518,189,40679
50,,,,,,,,,,,,,
51,Nord,14,39881,70678,5807,2918,455775,14,40441,67436,5136,2709,489952
52,Centro,22,43092,58101,6235,689,603194,22,54572,56599,6807,930,559938
53,Mezzogiorno,10,10436,20018,1362,1252,205816,10,8711,18252,1788,1310,208031
54,,,,,,,,,,,,,
55,Totale Italia,46,93409,148797,13404,4859,1264785,46,103724,142287,13731,4949,1257921

,Tav. 2 - Biblioteche statali dipendenti dal MiBact per tipologia e provincia e consistenza del patrimonio librario - Anni 2017-2018,Column3,Column4,Column5,Column6,Column8,Column9,Column10,Column11
0,PROVINCE E REGIONI,Volumi manoscritti,Volumi stampati,Opuscoli,Periodici,Volumi manoscritti,Volumi stampati,Opuscoli,Periodici
1,,,,,,,,,
2,,ANNO 2017,,,,ANNO 2018,,,
3,,,,,,,,,
4,Torino,8983,1003181,206644,922,8984,1011281,206954,1129
5,Piemonte,8983,1003181,206644,922,8984,1011281,206954,1129
6,Valle d'Aosta/Vall√©e d'Aoste,-,-,0,0,0,0,0,0
7,Genova,1949,430886,104262,-,1949,435568,104458,-
8,Liguria,1949,430886,104262,0,1949,435568,104458,0
9,Cremona,3880,485321,86974,1155,3880,487434,87032,1160
10,Milano,2122,1106953,299669,1851,2123,1125008,299669,1777
11,Pavia,1411,397495,120262,96,1411,400967,120365,259
12,Lombardia,7413,1989769,506905,3102,7414,2013409,507066,3196
13,Bolzano/Bozen,-,-,0,0,0,0,0,0
14,Trento,-,-,0,0,0,0,0,0
15,Trentino-Alto Adige,-,-,0,0,0,0,0,0
16,Padova,2960,621605,231358,374,2962,623242,231601,380
17,Venezia,13119,642710,264764,403,13122,644212,264867,403
18,Veneto,16079,1264315,496122,777,16084,1267454,496468,783
19,Gorizia,932,368016,85465,351,933,371265,86214,410
20,Trieste,8,192914,21036,118,8,192222,21412,98
21,Friuli-Venezia Giulia,940,560930,106501,469,941,563487,107626,508
22,Modena,11025,571792,130292,329,11025,572676,130420,325
23,Parma,52244,686798,131307,139,52244,687756,131307,57
24,Emilia-Romagna,63269,1258590,261599,468,63269,1260432,261727,382
25,Firenze,43493,6729059,2962717,13092,43495,6783628,2966591,12826
26,Lucca,4326,384567,88471,151,4326,385383,88559,148
27,Pisa,2571,585643,121478,-,2571,587667,121587,-
28,Toscana,50390,7699269,3172666,13243,50392,7756678,3176737,12974
29,Umbria,-,-,0,0,0,0,0,0
30,Macerata,64,82849,4060,-,64,83393,4068,-
31,Marche,64,82849,4060,0,64,83393,4068,0
32,Frosinone,2680,179499,5416,16,2702,180227,5424,16
33,Rieti,350,45065,2444,-,350,45193,2444,-
34,Roma,25584,7248156,2018127,24743,25587,7330272,2020133,25673
35,Lazio,28614,7472720,2025987,24759,28639,7555692,2028001,25689
36,Abruzzo,-,-,0,0,0,0,0,0
37,Molise,-,-,0,0,0,0,0,0
38,Avellino,580,159138,24473,24,580,159696,26291,39
39,Napoli,18594,2191705,455173,1372,18594,2195473,455549,955
40,Salerno,439,92140,8211,30,439,92511,8230,25
41,Campania,19613,2442983,487857,1426,19613,2447680,490070,1019
42,Bari,454,329311,65869,231,454,332520,65907,201
43,Puglia,454,329311,65869,231,454,332520,65907,201
44,Potenza,-,-,0,0,118,138420,11994,261
45,Basilicata,118,143672,12241,0,118,138420,11994,261
46,Cosenza,119,133618,16154,135,170,142897,16810,137
47,Calabria,119,133618,16154,135,170,142897,16810,137
48,Sicilia,-,-,0,0,0,0,0,0
49,Cagliari,604,548979,30319,712,604,550810,30319,712
50,Sassari,2374,217796,26898,2963,2374,222110,26997,2963
51,Sardegna,2978,766775,57217,3675,2978,772920,57316,3675
52,,,,,,,,,
53,Nord,98633,6507671,1682033,5738,98641,6551631,1684299,5998
54,Centro,79068,15254838,5202713,38002,79095,15395763,5208806,38663
55,Mezzogiorno,23282,3816359,639338,5467,23333,3834437,642097,5293
56,,,,,,,,,
57,Totale Italia,200983,25578868,7524084,49207,201069,25781831,7535202,49954

,"Tav. 3 - Biblioteche statali dipendenti dal MiBact, posti per lettori, lettori in totale e stranieri - Anni 2017 e 2018",Column2,Column4,Column5,Column8,Column9,Column11
0,PROVINCE E REGIONI,Posti per lettori,Lettori in totale,Lettori Stranieri,Posti per lettori,Lettori in totale,Lettori Stranieri
1,,,,,,,
2,,ANNO 2017,,,ANNO 2018,,
3,,,,,,,
4,Torino,301,55795,1981,301,61754,2098
5,Piemonte,301,55795,1981,301,61754,2098
6,Valle d'Aosta/Vall√©e d'Aoste,-,-,-,16,1216,-
7,Genova,60,21905,10953,144,16809,6500
8,Liguria,60,21905,10953,144,16809,6500
9,Cremona,220,90865,3417,220,95240,3387
10,Milano,240,58014,2075,240,40356,2018
11,Pavia,63,29779,2075,63,30363,2019
12,Lombardia,523,178658,7567,523,165959,7424
13,Bolzano/Bozen,-,-,-,-,-,-
14,Trento,-,-,-,-,-,-
15,Trentino-Alto Adige,-,-,-,-,-,-
16,Padova,252,36685,675,252,34175,171
17,Venezia,76,20849,1030,76,20018,1039
18,Veneto,328,57534,1705,328,54193,1210
19,Gorizia,102,27748,5653,102,28219,5460
20,Trieste,120,24047,72,120,23723,45
21,Friuli-Venezia Giulia,222,51795,5725,222,51942,5505
22,Modena,48,7161,326,48,6307,346
23,Parma,142,18066,1800,142,16835,1600
24,Emilia-Romagna,190,25227,2126,190,23142,1946
25,Firenze,589,108795,16659,589,131193,20503
26,Lucca,80,8711,17,80,7274,25
27,Pisa,30,2524,58,30,3507,62
28,Toscana,699,120030,16734,699,141974,20590
29,Umbria,-,0,0,-,0,0
30,Macerata,32,11992,510,32,10340,300
31,Marche,32,11992,510,32,10340,300
32,Frosinone,69,5970,276,69,4860,201
33,Rieti,40,390,10,40,395,12
34,Roma,1867,336026,22241,1837,328577,28419
35,Lazio,1976,342386,22527,1946,333832,28632
36,Abruzzo,-,0,0,-,0,0
37,Molise,-,0,0,-,0,0
38,Avellino,15,1136,1,15,949,9
39,Napoli,675,120520,0,675,134185,92
40,Salerno,18,431,44,18,509,38
41,Campania,708,122087,45,708,135643,139
42,Bari,230,14781,432,230,10294,43
43,Puglia,230,14781,432,230,10294,43
44,Potenza,313,29859,10,313,25975,254
45,Basilicata,313,29859,10,313,25975,254
46,Cosenza,65,6775,65,65,10713,32
47,Calabria,65,6775,65,65,10713,32
48,Sicilia,-,0,0,-,0,0
49,Cagliari,98,17816,6253,98,17825,7043
50,Sassari,85,9614,-,85,14380,-
51,Sardegna,183,27430,6253,183,32205,7043
52,,,,,,,
53,Nord,1624,390914,30057,1708,373799,24683
54,Centro,2707,474408,39771,2677,486146,49522
55,Mezzogiorno,1499,200932,6805,1499,214830,7511
56,,,,,,,
57,Totale Italia,5830,1066254,76633,5884,1074775,81716